(define (problem BLOCKS-11-2)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 e j d c f k h g a i b - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r0 r1 r3)
)
(:init
 (myAgent r2)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear e))
 (= (on e) g)
 (not (ontable e))
 (not (clear j))
 (= (on j) a)
 (not (ontable j))
 (not (clear d))
 (= (on d) j)
 (not (ontable d))
 (not (clear c))
 (= (on c) d)
 (not (ontable c))
 (not (clear f))
 (= (on f) c)
 (not (ontable f))
 (not (clear k))
 (= (on k) f)
 (not (ontable k))
 (not (clear h))
 (= (on h) k)
 (not (ontable h))
 (not (clear g))
 (ontable g)
 (= (on g) nob)
 (not (clear a))
 (ontable a)
 (= (on a) nob)
 (clear i)
 (= (on i) e)
 (not (ontable i))
 (clear b)
 (= (on b) h)
 (not (ontable b))
)
(:global-goal (and
 (= (on i) g)
 (= (on g) c)
 (= (on c) d)
 (= (on d) e)
 (= (on e) j)
 (= (on j) b)
 (= (on b) h)
 (= (on h) a)
 (= (on a) f)
 (= (on f) k)
)))
