(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
 satellite0 satellite1 - satellite
 instrument0 instrument1 instrument2 instrument3 - instrument
 image1 infrared0 spectrograph2 - mode
 star1 star2 star0 star3 star4 phenomenon5 phenomenon6 phenomenon7 - direction
)
(:shared-data
  ((pointing ?s - satellite) - direction)
  (have_image ?d - direction ?m - mode) - satellite0
)
(:init (mySatellite satellite1)
 (power_avail satellite1)
 (not (power_on instrument0))
 (not (calibrated instrument0))
 (= (calibration_target instrument0) star1)
 (not (power_on instrument1))
 (not (calibrated instrument1))
 (= (calibration_target instrument1) star2)
 (not (power_on instrument2))
 (not (calibrated instrument2))
 (= (calibration_target instrument2) star0)
 (not (power_on instrument3))
 (not (calibrated instrument3))
 (= (calibration_target instrument3) star0)
 (not (have_image star3 infrared0))
 (not (have_image star4 spectrograph2))
 (not (have_image phenomenon5 spectrograph2))
 (not (have_image phenomenon7 spectrograph2))
 (= (pointing satellite1) star0)
 (= (on_board satellite1) {instrument3})
 (not (= (on_board satellite1) {instrument0 instrument1 instrument2}))
 (= (supports instrument0) {infrared0 spectrograph2})
 (not (= (supports instrument0) {image1}))
 (= (supports instrument1) {image1})
 (not (= (supports instrument1) {infrared0 spectrograph2}))
 (= (supports instrument2) {image1 infrared0})
 (not (= (supports instrument2) {spectrograph2}))
 (= (supports instrument3) {image1 infrared0 spectrograph2})
 (not (= (supports instrument3) {}))
)
(:global-goal (and
 (= (pointing satellite0) phenomenon5)
 (have_image star3 infrared0)
 (have_image star4 spectrograph2)
 (have_image phenomenon5 spectrograph2)
 (have_image phenomenon7 spectrograph2)
))
)
