exclude: ^unified_planning/grpc/generated/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        # two trailing spaces are a hard line break in markdown
        args: [--markdown-linebreak-ext=md]
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: lint
        name: just lint
        entry: just lint
        language: system
        pass_filenames: false
