(define (problem BLOCKS-10-2)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 b g e d f h i a c j - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r0 r1 r2)
)
(:init
 (myAgent r3)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear b))
 (= (on b) a)
 (not (ontable b))
 (not (clear g))
 (= (on g) b)
 (not (ontable g))
 (not (clear e))
 (= (on e) g)
 (not (ontable e))
 (not (clear d))
 (= (on d) e)
 (not (ontable d))
 (not (clear f))
 (= (on f) d)
 (not (ontable f))
 (not (clear h))
 (= (on h) f)
 (not (ontable h))
 (not (clear i))
 (= (on i) h)
 (not (ontable i))
 (not (clear a))
 (ontable a)
 (= (on a) nob)
 (clear c)
 (ontable c)
 (= (on c) nob)
 (clear j)
 (= (on j) i)
 (not (ontable j))
)
(:global-goal (and
 (= (on b) e)
 (= (on e) i)
 (= (on i) g)
 (= (on g) h)
 (= (on h) c)
 (= (on c) a)
 (= (on a) f)
 (= (on f) j)
 (= (on j) d)
)))
