(define (problem BLOCKS-8-0)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 f b g c h e a d - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r0 r1 r2)
)
(:init
 (myAgent r3)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear f))
 (ontable f)
 (= (on f) nob)
 (clear b)
 (ontable b)
 (= (on b) nob)
 (not (clear g))
 (= (on g) e)
 (not (ontable g))
 (clear c)
 (ontable c)
 (= (on c) nob)
 (not (clear h))
 (= (on h) f)
 (not (ontable h))
 (not (clear e))
 (ontable e)
 (= (on e) nob)
 (clear a)
 (= (on a) g)
 (not (ontable a))
 (clear d)
 (= (on d) h)
 (not (ontable d))
)
(:global-goal (and
 (= (on d) f)
 (= (on f) e)
 (= (on e) h)
 (= (on h) c)
 (= (on c) a)
 (= (on a) g)
 (= (on g) b)
)))
