(define (problem BLOCKS-12-0)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 e l a b f i h g d j k c - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r0 r2 r3)
)
(:init
 (myAgent r1)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear e))
 (= (on e) b)
 (not (ontable e))
 (clear l)
 (= (on l) f)
 (not (ontable l))
 (not (clear a))
 (= (on a) g)
 (not (ontable a))
 (not (clear b))
 (= (on b) d)
 (not (ontable b))
 (not (clear f))
 (ontable f)
 (= (on f) nob)
 (not (clear i))
 (= (on i) c)
 (not (ontable i))
 (clear h)
 (= (on h) a)
 (not (ontable h))
 (not (clear g))
 (= (on g) k)
 (not (ontable g))
 (not (clear d))
 (= (on d) i)
 (not (ontable d))
 (clear j)
 (ontable j)
 (= (on j) nob)
 (not (clear k))
 (= (on k) e)
 (not (ontable k))
 (not (clear c))
 (ontable c)
 (= (on c) nob)
)
(:global-goal (and
 (= (on i) c)
 (= (on c) b)
 (= (on b) l)
 (= (on l) d)
 (= (on d) j)
 (= (on j) e)
 (= (on e) k)
 (= (on k) f)
 (= (on f) a)
 (= (on a) h)
 (= (on h) g)
)))
