(define (problem BLOCKS-9-1)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 h d i a e g b f c - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r0 r1 r2)
)
(:init
 (myAgent r3)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear h))
 (= (on h) a)
 (not (ontable h))
 (not (clear d))
 (= (on d) c)
 (not (ontable d))
 (not (clear i))
 (= (on i) g)
 (not (ontable i))
 (not (clear a))
 (ontable a)
 (= (on a) nob)
 (not (clear e))
 (= (on e) b)
 (not (ontable e))
 (not (clear g))
 (= (on g) h)
 (not (ontable g))
 (not (clear b))
 (= (on b) d)
 (not (ontable b))
 (clear f)
 (= (on f) e)
 (not (ontable f))
 (not (clear c))
 (= (on c) i)
 (not (ontable c))
)
(:global-goal (and
 (= (on d) i)
 (= (on i) a)
 (= (on a) b)
 (= (on b) h)
 (= (on h) g)
 (= (on g) f)
 (= (on f) e)
 (= (on e) c)
)))
