(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
 satellite0 satellite1 satellite2 satellite3 satellite4 satellite5 - satellite
 instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11 - instrument
 thermograph4 image1 thermograph3 image2 thermograph0 - mode
 groundstation3 groundstation4 groundstation2 groundstation0 groundstation1 phenomenon5 phenomenon6 phenomenon7 planet8 star9 star10 phenomenon11 phenomenon12 phenomenon13 star14 planet15 planet16 planet17 phenomenon18 star19 star20 planet21 star22 planet23 star24 - direction
)
(:shared-data
  ((pointing ?s - satellite) - direction)
  (have_image ?d - direction ?m - mode) - (either satellite0 satellite1 satellite2 satellite4 satellite5)
)
(:init (mySatellite satellite3)
 (power_avail satellite3)
 (not (power_on instrument0))
 (not (calibrated instrument0))
 (= (calibration_target instrument0) groundstation2)
 (not (power_on instrument1))
 (not (calibrated instrument1))
 (= (calibration_target instrument1) groundstation0)
 (not (power_on instrument2))
 (not (calibrated instrument2))
 (= (calibration_target instrument2) groundstation2)
 (not (power_on instrument3))
 (not (calibrated instrument3))
 (= (calibration_target instrument3) groundstation2)
 (not (power_on instrument4))
 (not (calibrated instrument4))
 (= (calibration_target instrument4) groundstation1)
 (not (power_on instrument5))
 (not (calibrated instrument5))
 (= (calibration_target instrument5) groundstation4)
 (not (power_on instrument6))
 (not (calibrated instrument6))
 (= (calibration_target instrument6) groundstation0)
 (not (power_on instrument7))
 (not (calibrated instrument7))
 (= (calibration_target instrument7) groundstation4)
 (not (power_on instrument8))
 (not (calibrated instrument8))
 (= (calibration_target instrument8) groundstation2)
 (not (power_on instrument9))
 (not (calibrated instrument9))
 (= (calibration_target instrument9) groundstation2)
 (not (power_on instrument10))
 (not (calibrated instrument10))
 (= (calibration_target instrument10) groundstation0)
 (not (power_on instrument11))
 (not (calibrated instrument11))
 (= (calibration_target instrument11) groundstation1)
 (not (have_image phenomenon5 image1))
 (not (have_image phenomenon7 thermograph0))
 (not (have_image planet8 image2))
 (not (have_image star9 thermograph0))
 (not (have_image star10 thermograph3))
 (not (have_image phenomenon12 thermograph0))
 (not (have_image phenomenon13 image1))
 (not (have_image star14 thermograph4))
 (not (have_image planet15 image2))
 (not (have_image planet17 image2))
 (not (have_image phenomenon18 image1))
 (not (have_image star19 thermograph4))
 (not (have_image star20 thermograph4))
 (not (have_image planet21 thermograph0))
 (not (have_image star22 thermograph3))
 (not (have_image planet23 image1))
 (= (pointing satellite3) groundstation4)
 (= (on_board satellite3) {instrument7 instrument8})
 (not (= (on_board satellite3) {instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument9 instrument10 instrument11}))
 (= (supports instrument0) {image1 thermograph0})
 (not (= (supports instrument0) {thermograph4 thermograph3 image2}))
 (= (supports instrument1) {thermograph3 image2})
 (not (= (supports instrument1) {thermograph4 image1 thermograph0}))
 (= (supports instrument2) {thermograph4 image1 thermograph3})
 (not (= (supports instrument2) {image2 thermograph0}))
 (= (supports instrument3) {thermograph4 image2 thermograph0})
 (not (= (supports instrument3) {image1 thermograph3}))
 (= (supports instrument4) {thermograph4 image1 thermograph0})
 (not (= (supports instrument4) {thermograph3 image2}))
 (= (supports instrument5) {thermograph4})
 (not (= (supports instrument5) {image1 thermograph3 image2 thermograph0}))
 (= (supports instrument6) {image1 thermograph3})
 (not (= (supports instrument6) {thermograph4 image2 thermograph0}))
 (= (supports instrument7) {thermograph3 image2})
 (not (= (supports instrument7) {thermograph4 image1 thermograph0}))
 (= (supports instrument8) {thermograph4 thermograph0})
 (not (= (supports instrument8) {image1 thermograph3 image2}))
 (= (supports instrument9) {image1 image2 thermograph0})
 (not (= (supports instrument9) {thermograph4 thermograph3}))
 (= (supports instrument10) {image1 thermograph3})
 (not (= (supports instrument10) {thermograph4 image2 thermograph0}))
 (= (supports instrument11) {image2 thermograph0})
 (not (= (supports instrument11) {thermograph4 image1 thermograph3}))
)
(:global-goal (and
 (= (pointing satellite0) planet21)
 (= (pointing satellite2) star14)
 (= (pointing satellite5) planet17)
 (have_image phenomenon5 image1)
 (have_image phenomenon7 thermograph0)
 (have_image planet8 image2)
 (have_image star9 thermograph0)
 (have_image star10 thermograph3)
 (have_image phenomenon12 thermograph0)
 (have_image phenomenon13 image1)
 (have_image star14 thermograph4)
 (have_image planet15 image2)
 (have_image planet17 image2)
 (have_image phenomenon18 image1)
 (have_image star19 thermograph4)
 (have_image star20 thermograph4)
 (have_image planet21 thermograph0)
 (have_image star22 thermograph3)
 (have_image planet23 image1)
))
)
