(define (problem depotprob7654) (:domain Depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate1)
	(at pallet1 depot1)
	(clear crate0)
	(at pallet2 depot2)
	(clear crate4)
	(at pallet3 distributor0)
	(clear crate5)
	(at pallet4 distributor1)
	(clear pallet4)
	(at pallet5 distributor2)
	(clear crate3)
	(at truck0 depot1)
	(= (speed truck0) 4)
	(at truck1 depot2)
	(= (speed truck1) 2)
	(at hoist0 depot0)
	(available hoist0)
	(= (power hoist0) 1)
	(at hoist1 depot1)
	(available hoist1)
	(= (power hoist1) 6)
	(at hoist2 depot2)
	(available hoist2)
	(= (power hoist2) 4)
	(at hoist3 distributor0)
	(available hoist3)
	(= (power hoist3) 1)
	(at hoist4 distributor1)
	(available hoist4)
	(= (power hoist4) 5)
	(at hoist5 distributor2)
	(available hoist5)
	(= (power hoist5) 4)
	(at crate0 depot1)
	(on crate0 pallet1)
	(= (weight crate0) 96)
	(at crate1 depot0)
	(on crate1 pallet0)
	(= (weight crate1) 72)
	(at crate2 distributor2)
	(on crate2 pallet5)
	(= (weight crate2) 74)
	(at crate3 distributor2)
	(on crate3 crate2)
	(= (weight crate3) 16)
	(at crate4 depot2)
	(on crate4 pallet2)
	(= (weight crate4) 24)
	(at crate5 distributor0)
	(on crate5 pallet3)
	(= (weight crate5) 42)
	(= (distance depot0 depot0) 0)
	(= (distance depot0 depot1) 2)
	(= (distance depot0 depot2) 10)
	(= (distance depot0 distributor0) 6)
	(= (distance depot0 distributor1) 1)
	(= (distance depot0 distributor2) 7)
	(= (distance depot1 depot0) 3)
	(= (distance depot1 depot1) 0)
	(= (distance depot1 depot2) 3)
	(= (distance depot1 distributor0) 1)
	(= (distance depot1 distributor1) 10)
	(= (distance depot1 distributor2) 3)
	(= (distance depot2 depot0) 7)
	(= (distance depot2 depot1) 3)
	(= (distance depot2 depot2) 0)
	(= (distance depot2 distributor0) 7)
	(= (distance depot2 distributor1) 2)
	(= (distance depot2 distributor2) 6)
	(= (distance distributor0 depot0) 4)
	(= (distance distributor0 depot1) 10)
	(= (distance distributor0 depot2) 6)
	(= (distance distributor0 distributor0) 0)
	(= (distance distributor0 distributor1) 8)
	(= (distance distributor0 distributor2) 3)
	(= (distance distributor1 depot0) 5)
	(= (distance distributor1 depot1) 3)
	(= (distance distributor1 depot2) 4)
	(= (distance distributor1 distributor0) 3)
	(= (distance distributor1 distributor1) 0)
	(= (distance distributor1 distributor2) 10)
	(= (distance distributor2 depot0) 7)
	(= (distance distributor2 depot1) 6)
	(= (distance distributor2 depot2) 1)
	(= (distance distributor2 distributor0) 6)
	(= (distance distributor2 distributor1) 2)
	(= (distance distributor2 distributor2) 0)
)

(:goal (and
		(on crate0 crate4)
		(on crate2 pallet3)
		(on crate3 pallet0)
		(on crate4 pallet5)
	)
)

;(:metric minimize (total-time))
)
