(define (problem BLOCKS-16-2)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 k i g n p a d m c b h f o j l e - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r1 r2 r3)
)
(:init
 (myAgent r0)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear k))
 (= (on k) j)
 (not (ontable k))
 (not (clear i))
 (= (on i) k)
 (not (ontable i))
 (not (clear g))
 (= (on g) i)
 (not (ontable g))
 (not (clear n))
 (= (on n) g)
 (not (ontable n))
 (not (clear p))
 (= (on p) n)
 (not (ontable p))
 (not (clear a))
 (= (on a) p)
 (not (ontable a))
 (not (clear d))
 (= (on d) a)
 (not (ontable d))
 (not (clear m))
 (= (on m) d)
 (not (ontable m))
 (not (clear c))
 (= (on c) m)
 (not (ontable c))
 (not (clear b))
 (= (on b) c)
 (not (ontable b))
 (not (clear h))
 (= (on h) b)
 (not (ontable h))
 (not (clear f))
 (= (on f) h)
 (not (ontable f))
 (not (clear o))
 (ontable o)
 (= (on o) nob)
 (not (clear j))
 (ontable j)
 (= (on j) nob)
 (clear l)
 (= (on l) o)
 (not (ontable l))
 (clear e)
 (= (on e) f)
 (not (ontable e))
)
(:global-goal (and
 (= (on i) d)
 (= (on d) h)
 (= (on h) f)
 (= (on f) b)
 (= (on b) k)
 (= (on k) j)
 (= (on j) g)
 (= (on g) e)
 (= (on e) c)
 (= (on c) l)
 (= (on l) m)
 (= (on m) n)
 (= (on n) a)
 (= (on a) p)
 (= (on p) o)
)))
