(define (problem roverprob2312)
(:domain rover)
(:objects
 rover0 rover1 - rover
 waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 - waypoint
 rover0store rover1store - store
 camera0 camera1 camera2 - camera
 colour high_res low_res - mode
 general - lander
 objective0 objective1 - objective
)
(:shared-data
  (communicated_soil_data ?w - waypoint)
  (communicated_rock_data ?w - waypoint)
  (communicated_image_data ?o - objective ?m - mode)
  (at_soil_sample ?w - waypoint)
  (at_rock_sample ?w - waypoint) -
rover0
)
(:init (myRover rover1)
 (equipped_for_soil_analysis rover1)
 (not (equipped_for_rock_analysis rover1))
 (equipped_for_imaging rover1)
 (empty rover0store)
 (empty rover1store)
 (not (full rover0store))
 (not (full rover1store))
 (not (can_traverse rover1 waypoint0 waypoint0))
 (can_traverse rover1 waypoint0 waypoint1)
 (not (can_traverse rover1 waypoint0 waypoint2))
 (not (can_traverse rover1 waypoint0 waypoint3))
 (not (can_traverse rover1 waypoint0 waypoint4))
 (not (can_traverse rover1 waypoint0 waypoint5))
 (can_traverse rover1 waypoint1 waypoint0)
 (not (can_traverse rover1 waypoint1 waypoint1))
 (not (can_traverse rover1 waypoint1 waypoint2))
 (not (can_traverse rover1 waypoint1 waypoint3))
 (can_traverse rover1 waypoint1 waypoint4)
 (not (can_traverse rover1 waypoint1 waypoint5))
 (not (can_traverse rover1 waypoint2 waypoint0))
 (not (can_traverse rover1 waypoint2 waypoint1))
 (not (can_traverse rover1 waypoint2 waypoint2))
 (not (can_traverse rover1 waypoint2 waypoint3))
 (not (can_traverse rover1 waypoint2 waypoint4))
 (can_traverse rover1 waypoint2 waypoint5)
 (not (can_traverse rover1 waypoint3 waypoint0))
 (not (can_traverse rover1 waypoint3 waypoint1))
 (not (can_traverse rover1 waypoint3 waypoint2))
 (not (can_traverse rover1 waypoint3 waypoint3))
 (can_traverse rover1 waypoint3 waypoint4)
 (not (can_traverse rover1 waypoint3 waypoint5))
 (not (can_traverse rover1 waypoint4 waypoint0))
 (can_traverse rover1 waypoint4 waypoint1)
 (not (can_traverse rover1 waypoint4 waypoint2))
 (can_traverse rover1 waypoint4 waypoint3)
 (not (can_traverse rover1 waypoint4 waypoint4))
 (can_traverse rover1 waypoint4 waypoint5)
 (not (can_traverse rover1 waypoint5 waypoint0))
 (not (can_traverse rover1 waypoint5 waypoint1))
 (can_traverse rover1 waypoint5 waypoint2)
 (not (can_traverse rover1 waypoint5 waypoint3))
 (can_traverse rover1 waypoint5 waypoint4)
 (not (can_traverse rover1 waypoint5 waypoint5))
 (not (have_rock_analysis rover1 waypoint0))
 (not (have_rock_analysis rover1 waypoint1))
 (not (have_rock_analysis rover1 waypoint2))
 (not (have_rock_analysis rover1 waypoint3))
 (not (have_rock_analysis rover1 waypoint4))
 (not (have_rock_analysis rover1 waypoint5))
 (not (have_soil_analysis rover1 waypoint0))
 (not (have_soil_analysis rover1 waypoint1))
 (not (have_soil_analysis rover1 waypoint2))
 (not (have_soil_analysis rover1 waypoint3))
 (not (have_soil_analysis rover1 waypoint4))
 (not (have_soil_analysis rover1 waypoint5))
 (not (visible waypoint0 waypoint0))
 (visible waypoint0 waypoint1)
 (visible waypoint0 waypoint2)
 (visible waypoint0 waypoint3)
 (not (visible waypoint0 waypoint4))
 (visible waypoint0 waypoint5)
 (visible waypoint1 waypoint0)
 (not (visible waypoint1 waypoint1))
 (not (visible waypoint1 waypoint2))
 (visible waypoint1 waypoint3)
 (visible waypoint1 waypoint4)
 (not (visible waypoint1 waypoint5))
 (visible waypoint2 waypoint0)
 (not (visible waypoint2 waypoint1))
 (not (visible waypoint2 waypoint2))
 (visible waypoint2 waypoint3)
 (not (visible waypoint2 waypoint4))
 (visible waypoint2 waypoint5)
 (visible waypoint3 waypoint0)
 (visible waypoint3 waypoint1)
 (visible waypoint3 waypoint2)
 (not (visible waypoint3 waypoint3))
 (visible waypoint3 waypoint4)
 (visible waypoint3 waypoint5)
 (not (visible waypoint4 waypoint0))
 (visible waypoint4 waypoint1)
 (not (visible waypoint4 waypoint2))
 (visible waypoint4 waypoint3)
 (not (visible waypoint4 waypoint4))
 (visible waypoint4 waypoint5)
 (visible waypoint5 waypoint0)
 (not (visible waypoint5 waypoint1))
 (visible waypoint5 waypoint2)
 (visible waypoint5 waypoint3)
 (visible waypoint5 waypoint4)
 (not (visible waypoint5 waypoint5))
 (not (communicated_soil_data waypoint0))
 (not (communicated_soil_data waypoint1))
 (not (communicated_soil_data waypoint2))
 (not (communicated_soil_data waypoint3))
 (not (communicated_soil_data waypoint4))
 (not (communicated_soil_data waypoint5))
 (not (communicated_rock_data waypoint0))
 (not (communicated_rock_data waypoint1))
 (not (communicated_rock_data waypoint2))
 (not (communicated_rock_data waypoint3))
 (not (communicated_rock_data waypoint4))
 (not (communicated_rock_data waypoint5))
 (not (at_soil_sample waypoint0))
 (at_soil_sample waypoint1)
 (at_soil_sample waypoint2)
 (at_soil_sample waypoint3)
 (at_soil_sample waypoint4)
 (at_soil_sample waypoint5)
 (at_rock_sample waypoint0)
 (not (at_rock_sample waypoint1))
 (at_rock_sample waypoint2)
 (at_rock_sample waypoint3)
 (not (at_rock_sample waypoint4))
 (at_rock_sample waypoint5)
 (not (calibrated camera0 rover1))
 (not (calibrated camera1 rover1))
 (not (calibrated camera2 rover1))
 (supports camera0 colour)
 (not (supports camera0 high_res))
 (supports camera0 low_res)
 (supports camera1 colour)
 (not (supports camera1 high_res))
 (supports camera1 low_res)
 (supports camera2 colour)
 (supports camera2 high_res)
 (not (supports camera2 low_res))
 (not (have_image rover1 objective0 colour))
 (not (have_image rover1 objective0 high_res))
 (not (have_image rover1 objective0 low_res))
 (not (have_image rover1 objective1 colour))
 (not (have_image rover1 objective1 high_res))
 (not (have_image rover1 objective1 low_res))
 (not (communicated_image_data objective0 colour))
 (not (communicated_image_data objective0 high_res))
 (not (communicated_image_data objective0 low_res))
 (not (communicated_image_data objective1 colour))
 (not (communicated_image_data objective1 high_res))
 (not (communicated_image_data objective1 low_res))
 (visible_from objective0 waypoint0)
 (visible_from objective0 waypoint1)
 (visible_from objective0 waypoint2)
 (visible_from objective0 waypoint3)
 (visible_from objective0 waypoint4)
 (visible_from objective0 waypoint5)
 (visible_from objective1 waypoint0)
 (visible_from objective1 waypoint1)
 (not (visible_from objective1 waypoint2))
 (not (visible_from objective1 waypoint3))
 (not (visible_from objective1 waypoint4))
 (not (visible_from objective1 waypoint5))
 (= (at rover1) waypoint4)
 (= (at_lander general) waypoint3)
 (= (store_of rover0store) rover0)
 (= (store_of rover1store) rover1)
 (= (calibration_target camera0) objective0)
 (= (calibration_target camera1) objective1)
 (= (calibration_target camera2) objective0)
 (= (on_board camera0) rover0)
 (= (on_board camera1) rover0)
 (= (on_board camera2) rover1)
)
(:global-goal (and
 (communicated_soil_data waypoint5)
 (communicated_soil_data waypoint1)
 (communicated_soil_data waypoint4)
 (communicated_soil_data waypoint2)
 (communicated_rock_data waypoint0)
 (communicated_rock_data waypoint2)
 (communicated_rock_data waypoint3)
 (communicated_image_data objective0 colour)
 (communicated_image_data objective1 low_res)
 (communicated_image_data objective0 low_res)
))
)
