(define (problem BLOCKS-15-0)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 j b k a d h e n c f l m i o g - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r0 r1 r3)
)
(:init
 (myAgent r2)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear j))
 (= (on j) d)
 (not (ontable j))
 (clear b)
 (= (on b) a)
 (not (ontable b))
 (not (clear k))
 (ontable k)
 (= (on k) nob)
 (not (clear a))
 (= (on a) o)
 (not (ontable a))
 (not (clear d))
 (= (on d) l)
 (not (ontable d))
 (not (clear h))
 (ontable h)
 (= (on h) nob)
 (clear e)
 (= (on e) j)
 (not (ontable e))
 (not (clear n))
 (ontable n)
 (= (on n) nob)
 (not (clear c))
 (= (on c) g)
 (not (ontable c))
 (clear f)
 (= (on f) k)
 (not (ontable f))
 (not (clear l))
 (= (on l) c)
 (not (ontable l))
 (clear m)
 (= (on m) n)
 (not (ontable m))
 (clear i)
 (= (on i) h)
 (not (ontable i))
 (not (clear o))
 (ontable o)
 (= (on o) nob)
 (not (clear g))
 (ontable g)
 (= (on g) nob)
)
(:global-goal (and
 (= (on g) o)
 (= (on o) h)
 (= (on h) k)
 (= (on k) m)
 (= (on m) f)
 (= (on f) e)
 (= (on e) a)
 (= (on a) b)
 (= (on b) l)
 (= (on l) j)
 (= (on j) d)
 (= (on d) n)
 (= (on n) i)
 (= (on i) c)
)))
