(define (problem BLOCKS-9-0)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 h d i a e g b f c - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r0 r2 r3)
)
(:init
 (myAgent r1)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear h))
 (= (on h) b)
 (not (ontable h))
 (not (clear d))
 (= (on d) h)
 (not (ontable d))
 (not (clear i))
 (= (on i) d)
 (not (ontable i))
 (not (clear a))
 (= (on a) i)
 (not (ontable a))
 (not (clear e))
 (= (on e) a)
 (not (ontable e))
 (not (clear g))
 (= (on g) e)
 (not (ontable g))
 (not (clear b))
 (ontable b)
 (= (on b) nob)
 (clear f)
 (= (on f) g)
 (not (ontable f))
 (clear c)
 (ontable c)
 (= (on c) nob)
)
(:global-goal (and
 (= (on g) d)
 (= (on d) b)
 (= (on b) c)
 (= (on c) a)
 (= (on a) i)
 (= (on i) f)
 (= (on f) e)
 (= (on e) h)
)))
