(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
 satellite0 satellite1 satellite2 satellite3 satellite4 - satellite
 instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11 instrument12 - instrument
 image1 thermograph3 thermograph0 thermograph2 thermograph4 - mode
 groundstation2 star4 star0 star1 star3 phenomenon5 planet6 planet7 star8 star9 star10 planet11 phenomenon12 phenomenon13 planet14 star15 phenomenon16 phenomenon17 phenomenon18 planet19 planet20 phenomenon21 star22 planet23 phenomenon24 - direction
)
(:shared-data
  ((pointing ?s - satellite) - direction)
  (have_image ?d - direction ?m - mode) - (either satellite0 satellite1 satellite2 satellite3)
)
(:init (mySatellite satellite4)
 (power_avail satellite4)
 (not (power_on instrument0))
 (not (calibrated instrument0))
 (= (calibration_target instrument0) star4)
 (not (power_on instrument1))
 (not (calibrated instrument1))
 (= (calibration_target instrument1) star0)
 (not (power_on instrument2))
 (not (calibrated instrument2))
 (= (calibration_target instrument2) star4)
 (not (power_on instrument3))
 (not (calibrated instrument3))
 (= (calibration_target instrument3) star1)
 (not (power_on instrument4))
 (not (calibrated instrument4))
 (= (calibration_target instrument4) star1)
 (not (power_on instrument5))
 (not (calibrated instrument5))
 (= (calibration_target instrument5) star3)
 (not (power_on instrument6))
 (not (calibrated instrument6))
 (= (calibration_target instrument6) star0)
 (not (power_on instrument7))
 (not (calibrated instrument7))
 (= (calibration_target instrument7) star3)
 (not (power_on instrument8))
 (not (calibrated instrument8))
 (= (calibration_target instrument8) star3)
 (not (power_on instrument9))
 (not (calibrated instrument9))
 (= (calibration_target instrument9) star1)
 (not (power_on instrument10))
 (not (calibrated instrument10))
 (= (calibration_target instrument10) star3)
 (not (power_on instrument11))
 (not (calibrated instrument11))
 (= (calibration_target instrument11) star1)
 (not (power_on instrument12))
 (not (calibrated instrument12))
 (= (calibration_target instrument12) star3)
 (not (have_image phenomenon5 thermograph4))
 (not (have_image planet7 image1))
 (not (have_image star8 thermograph3))
 (not (have_image star9 image1))
 (not (have_image star10 image1))
 (not (have_image phenomenon13 thermograph2))
 (not (have_image star15 thermograph2))
 (not (have_image phenomenon17 thermograph4))
 (not (have_image phenomenon18 image1))
 (not (have_image planet19 thermograph2))
 (not (have_image planet20 thermograph4))
 (not (have_image phenomenon21 image1))
 (not (have_image star22 thermograph3))
 (= (pointing satellite4) phenomenon18)
 (= (on_board satellite4) {instrument12})
 (not (= (on_board satellite4) {instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11}))
 (= (supports instrument0) {thermograph0 thermograph2 thermograph4})
 (not (= (supports instrument0) {image1 thermograph3}))
 (= (supports instrument1) {thermograph3})
 (not (= (supports instrument1) {image1 thermograph0 thermograph2 thermograph4}))
 (= (supports instrument2) {image1})
 (not (= (supports instrument2) {thermograph3 thermograph0 thermograph2 thermograph4}))
 (= (supports instrument3) {thermograph3})
 (not (= (supports instrument3) {image1 thermograph0 thermograph2 thermograph4}))
 (= (supports instrument4) {image1})
 (not (= (supports instrument4) {thermograph3 thermograph0 thermograph2 thermograph4}))
 (= (supports instrument5) {thermograph3})
 (not (= (supports instrument5) {image1 thermograph0 thermograph2 thermograph4}))
 (= (supports instrument6) {image1 thermograph0 thermograph2})
 (not (= (supports instrument6) {thermograph3 thermograph4}))
 (= (supports instrument7) {thermograph0})
 (not (= (supports instrument7) {image1 thermograph3 thermograph2 thermograph4}))
 (= (supports instrument8) {thermograph3 thermograph2 thermograph4})
 (not (= (supports instrument8) {image1 thermograph0}))
 (= (supports instrument9) {thermograph3 thermograph2})
 (not (= (supports instrument9) {image1 thermograph0 thermograph4}))
 (= (supports instrument10) {thermograph2})
 (not (= (supports instrument10) {image1 thermograph3 thermograph0 thermograph4}))
 (= (supports instrument11) {thermograph0 thermograph2 thermograph4})
 (not (= (supports instrument11) {image1 thermograph3}))
 (= (supports instrument12) {thermograph4})
 (not (= (supports instrument12) {image1 thermograph3 thermograph0 thermograph2}))
)
(:global-goal (and
 (have_image phenomenon5 thermograph4)
 (have_image planet7 image1)
 (have_image star8 thermograph3)
 (have_image star9 image1)
 (have_image star10 image1)
 (have_image phenomenon13 thermograph2)
 (have_image star15 thermograph2)
 (have_image phenomenon17 thermograph4)
 (have_image phenomenon18 image1)
 (have_image planet19 thermograph2)
 (have_image planet20 thermograph4)
 (have_image phenomenon21 image1)
 (have_image star22 thermograph3)
))
)
