# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='upf.proto',
  package='upf_plan',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tupf.proto\x12\x08upf_plan\"<\n\x06\x46luent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tvalueType\x18\x02 \x01(\t\x12\x11\n\tsignature\x18\x03 \x03(\t\"$\n\x06Object\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"b\n\nExpression\x12\x0c\n\x04type\x18\x01 \x01(\x03\x12\"\n\x04\x61rgs\x18\x02 \x03(\x0b\x32\x14.upf_plan.Expression\x12\"\n\x07payload\x18\x03 \x01(\x0b\x32\x11.upf_plan.Payload\"N\n\nAssignment\x12\x1f\n\x01x\x18\x01 \x01(\x0b\x32\x14.upf_plan.Expression\x12\x1f\n\x01v\x18\x02 \x01(\x0b\x32\x14.upf_plan.Expression\"&\n\x07Payload\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x96\x01\n\x06\x41\x63tion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nparameters\x18\x02 \x03(\t\x12\x16\n\x0eparameterTypes\x18\x03 \x03(\t\x12+\n\rpreconditions\x18\x04 \x03(\x0b\x32\x14.upf_plan.Expression\x12%\n\x07\x65\x66\x66\x65\x63ts\x18\x05 \x03(\x0b\x32\x14.upf_plan.Assignment\"\xd1\x01\n\x07Problem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\x07\x66luents\x18\x02 \x03(\x0b\x32\x10.upf_plan.Fluent\x12!\n\x07objects\x18\x03 \x03(\x0b\x32\x10.upf_plan.Object\x12!\n\x07\x61\x63tions\x18\x04 \x03(\x0b\x32\x10.upf_plan.Action\x12*\n\x0cinitialState\x18\x05 \x03(\x0b\x32\x14.upf_plan.Assignment\x12#\n\x05goals\x18\x06 \x03(\x0b\x32\x14.upf_plan.Expression\">\n\x0e\x41\x63tionInstance\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x03(\t\";\n\x0eSequentialPlan\x12)\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x18.upf_plan.ActionInstance\"D\n\x06\x41nswer\x12\x12\n\nplanExists\x18\x01 \x01(\x08\x12&\n\x04plan\x18\x02 \x01(\x0b\x32\x18.upf_plan.SequentialPlan2:\n\x03Upf\x12\x33\n\x04plan\x12\x11.upf_plan.Problem\x1a\x18.upf_plan.SequentialPlanb\x06proto3'
)




_FLUENT = _descriptor.Descriptor(
  name='Fluent',
  full_name='upf_plan.Fluent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='upf_plan.Fluent.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valueType', full_name='upf_plan.Fluent.valueType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='upf_plan.Fluent.signature', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=83,
)


_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='upf_plan.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='upf_plan.Object.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='upf_plan.Object.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=121,
)


_EXPRESSION = _descriptor.Descriptor(
  name='Expression',
  full_name='upf_plan.Expression',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='upf_plan.Expression.type', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='upf_plan.Expression.args', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='upf_plan.Expression.payload', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=221,
)


_ASSIGNMENT = _descriptor.Descriptor(
  name='Assignment',
  full_name='upf_plan.Assignment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='upf_plan.Assignment.x', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='v', full_name='upf_plan.Assignment.v', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=301,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='upf_plan.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='upf_plan.Payload.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='upf_plan.Payload.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=341,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='upf_plan.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='upf_plan.Action.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='upf_plan.Action.parameters', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameterTypes', full_name='upf_plan.Action.parameterTypes', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preconditions', full_name='upf_plan.Action.preconditions', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='effects', full_name='upf_plan.Action.effects', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=494,
)


_PROBLEM = _descriptor.Descriptor(
  name='Problem',
  full_name='upf_plan.Problem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='upf_plan.Problem.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fluents', full_name='upf_plan.Problem.fluents', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='objects', full_name='upf_plan.Problem.objects', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actions', full_name='upf_plan.Problem.actions', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initialState', full_name='upf_plan.Problem.initialState', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goals', full_name='upf_plan.Problem.goals', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=706,
)


_ACTIONINSTANCE = _descriptor.Descriptor(
  name='ActionInstance',
  full_name='upf_plan.ActionInstance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='upf_plan.ActionInstance.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='upf_plan.ActionInstance.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='upf_plan.ActionInstance.parameters', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=770,
)


_SEQUENTIALPLAN = _descriptor.Descriptor(
  name='SequentialPlan',
  full_name='upf_plan.SequentialPlan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='actions', full_name='upf_plan.SequentialPlan.actions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=772,
  serialized_end=831,
)


_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='upf_plan.Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='planExists', full_name='upf_plan.Answer.planExists', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='plan', full_name='upf_plan.Answer.plan', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=833,
  serialized_end=901,
)

_EXPRESSION.fields_by_name['args'].message_type = _EXPRESSION
_EXPRESSION.fields_by_name['payload'].message_type = _PAYLOAD
_ASSIGNMENT.fields_by_name['x'].message_type = _EXPRESSION
_ASSIGNMENT.fields_by_name['v'].message_type = _EXPRESSION
_ACTION.fields_by_name['preconditions'].message_type = _EXPRESSION
_ACTION.fields_by_name['effects'].message_type = _ASSIGNMENT
_PROBLEM.fields_by_name['fluents'].message_type = _FLUENT
_PROBLEM.fields_by_name['objects'].message_type = _OBJECT
_PROBLEM.fields_by_name['actions'].message_type = _ACTION
_PROBLEM.fields_by_name['initialState'].message_type = _ASSIGNMENT
_PROBLEM.fields_by_name['goals'].message_type = _EXPRESSION
_SEQUENTIALPLAN.fields_by_name['actions'].message_type = _ACTIONINSTANCE
_ANSWER.fields_by_name['plan'].message_type = _SEQUENTIALPLAN
DESCRIPTOR.message_types_by_name['Fluent'] = _FLUENT
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['Expression'] = _EXPRESSION
DESCRIPTOR.message_types_by_name['Assignment'] = _ASSIGNMENT
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['Problem'] = _PROBLEM
DESCRIPTOR.message_types_by_name['ActionInstance'] = _ACTIONINSTANCE
DESCRIPTOR.message_types_by_name['SequentialPlan'] = _SEQUENTIALPLAN
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fluent = _reflection.GeneratedProtocolMessageType('Fluent', (_message.Message,), {
  'DESCRIPTOR' : _FLUENT,
  '__module__' : 'upf_pb2'
  # @@protoc_insertion_point(class_scope:upf_plan.Fluent)
  })
_sym_db.RegisterMessage(Fluent)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT,
  '__module__' : 'upf_pb2'
  # @@protoc_insertion_point(class_scope:upf_plan.Object)
  })
_sym_db.RegisterMessage(Object)

Expression = _reflection.GeneratedProtocolMessageType('Expression', (_message.Message,), {
  'DESCRIPTOR' : _EXPRESSION,
  '__module__' : 'upf_pb2'
  # @@protoc_insertion_point(class_scope:upf_plan.Expression)
  })
_sym_db.RegisterMessage(Expression)

Assignment = _reflection.GeneratedProtocolMessageType('Assignment', (_message.Message,), {
  'DESCRIPTOR' : _ASSIGNMENT,
  '__module__' : 'upf_pb2'
  # @@protoc_insertion_point(class_scope:upf_plan.Assignment)
  })
_sym_db.RegisterMessage(Assignment)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOAD,
  '__module__' : 'upf_pb2'
  # @@protoc_insertion_point(class_scope:upf_plan.Payload)
  })
_sym_db.RegisterMessage(Payload)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'upf_pb2'
  # @@protoc_insertion_point(class_scope:upf_plan.Action)
  })
_sym_db.RegisterMessage(Action)

Problem = _reflection.GeneratedProtocolMessageType('Problem', (_message.Message,), {
  'DESCRIPTOR' : _PROBLEM,
  '__module__' : 'upf_pb2'
  # @@protoc_insertion_point(class_scope:upf_plan.Problem)
  })
_sym_db.RegisterMessage(Problem)

ActionInstance = _reflection.GeneratedProtocolMessageType('ActionInstance', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONINSTANCE,
  '__module__' : 'upf_pb2'
  # @@protoc_insertion_point(class_scope:upf_plan.ActionInstance)
  })
_sym_db.RegisterMessage(ActionInstance)

SequentialPlan = _reflection.GeneratedProtocolMessageType('SequentialPlan', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENTIALPLAN,
  '__module__' : 'upf_pb2'
  # @@protoc_insertion_point(class_scope:upf_plan.SequentialPlan)
  })
_sym_db.RegisterMessage(SequentialPlan)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), {
  'DESCRIPTOR' : _ANSWER,
  '__module__' : 'upf_pb2'
  # @@protoc_insertion_point(class_scope:upf_plan.Answer)
  })
_sym_db.RegisterMessage(Answer)



_UPF = _descriptor.ServiceDescriptor(
  name='Upf',
  full_name='upf_plan.Upf',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=903,
  serialized_end=961,
  methods=[
  _descriptor.MethodDescriptor(
    name='plan',
    full_name='upf_plan.Upf.plan',
    index=0,
    containing_service=None,
    input_type=_PROBLEM,
    output_type=_SEQUENTIALPLAN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPF)

DESCRIPTOR.services_by_name['Upf'] = _UPF

# @@protoc_insertion_point(module_scope)
