(define (problem depotprob6512)
(:domain depot)
(:objects
 depot0 - depot
 distributor0 distributor1 - distributor
 truck0 truck1 - truck
 crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 - crate
 pallet0 pallet1 pallet2 - pallet
 hoist0 hoist1 hoist2 - hoist
)
(:shared-data
  (clear ?x - (either surface hoist))
  ((at ?t - truck) - place)
  ((pos ?c - crate) - (either place truck))
  ((on ?c - crate) - (either surface hoist truck)) - 
(either depot0 distributor0 distributor1 truck0)
)
(:init
 (myAgent truck1)
 (= (pos crate0) depot0)
 (not (clear crate0))
 (= (on crate0) pallet0)
 (= (pos crate1) depot0)
 (not (clear crate1))
 (= (on crate1) crate0)
 (= (pos crate2) distributor0)
 (clear crate2)
 (= (on crate2) pallet1)
 (= (pos crate3) distributor1)
 (not (clear crate3))
 (= (on crate3) pallet2)
 (= (pos crate4) depot0)
 (not (clear crate4))
 (= (on crate4) crate1)
 (= (pos crate5) distributor1)
 (not (clear crate5))
 (= (on crate5) crate3)
 (= (pos crate6) distributor1)
 (clear crate6)
 (= (on crate6) crate5)
 (= (pos crate7) depot0)
 (clear crate7)
 (= (on crate7) crate4)
 (= (at truck0) distributor1)
 (= (at truck1) distributor1)
 (= (located hoist0) depot0)
 (clear hoist0)
 (= (located hoist1) distributor0)
 (clear hoist1)
 (= (located hoist2) distributor1)
 (clear hoist2)
 (= (placed pallet0) depot0)
 (not (clear pallet0))
 (= (placed pallet1) distributor0)
 (not (clear pallet1))
 (= (placed pallet2) distributor1)
 (not (clear pallet2))
)
(:global-goal (and
 (= (on crate0) crate4)
 (= (on crate2) crate6)
 (= (on crate4) crate7)
 (= (on crate5) pallet2)
 (= (on crate6) pallet1)
 (= (on crate7) pallet0)
))
)
