(define (problem roverprob7182)
(:domain rover)
(:objects
 rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 - rover
 waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 - waypoint
 rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store - store
 camera0 camera1 camera2 camera3 camera4 camera5 camera6 - camera
 colour high_res low_res - mode
 general - lander
 objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - objective
)
(:shared-data
  (communicated_soil_data ?w - waypoint)
  (communicated_rock_data ?w - waypoint)
  (communicated_image_data ?o - objective ?m - mode)
  (at_soil_sample ?w - waypoint)
  (at_rock_sample ?w - waypoint) -
(either rover0 rover1 rover3 rover4 rover5 rover6 rover7)
)
(:init (myRover rover2)
 (not (equipped_for_soil_analysis rover2))
 (equipped_for_rock_analysis rover2)
 (equipped_for_imaging rover2)
 (empty rover0store)
 (empty rover1store)
 (empty rover2store)
 (empty rover3store)
 (empty rover4store)
 (empty rover5store)
 (empty rover6store)
 (empty rover7store)
 (not (full rover0store))
 (not (full rover1store))
 (not (full rover2store))
 (not (full rover3store))
 (not (full rover4store))
 (not (full rover5store))
 (not (full rover6store))
 (not (full rover7store))
 (not (can_traverse rover2 waypoint0 waypoint0))
 (not (can_traverse rover2 waypoint0 waypoint1))
 (not (can_traverse rover2 waypoint0 waypoint2))
 (not (can_traverse rover2 waypoint0 waypoint3))
 (not (can_traverse rover2 waypoint0 waypoint4))
 (can_traverse rover2 waypoint0 waypoint5)
 (not (can_traverse rover2 waypoint0 waypoint6))
 (not (can_traverse rover2 waypoint0 waypoint7))
 (not (can_traverse rover2 waypoint0 waypoint8))
 (not (can_traverse rover2 waypoint0 waypoint9))
 (not (can_traverse rover2 waypoint0 waypoint10))
 (not (can_traverse rover2 waypoint0 waypoint11))
 (not (can_traverse rover2 waypoint0 waypoint12))
 (not (can_traverse rover2 waypoint0 waypoint13))
 (not (can_traverse rover2 waypoint0 waypoint14))
 (not (can_traverse rover2 waypoint0 waypoint15))
 (not (can_traverse rover2 waypoint0 waypoint16))
 (not (can_traverse rover2 waypoint0 waypoint17))
 (not (can_traverse rover2 waypoint0 waypoint18))
 (not (can_traverse rover2 waypoint0 waypoint19))
 (not (can_traverse rover2 waypoint0 waypoint20))
 (not (can_traverse rover2 waypoint0 waypoint21))
 (not (can_traverse rover2 waypoint0 waypoint22))
 (not (can_traverse rover2 waypoint0 waypoint23))
 (not (can_traverse rover2 waypoint0 waypoint24))
 (not (can_traverse rover2 waypoint1 waypoint0))
 (not (can_traverse rover2 waypoint1 waypoint1))
 (can_traverse rover2 waypoint1 waypoint2)
 (can_traverse rover2 waypoint1 waypoint3)
 (not (can_traverse rover2 waypoint1 waypoint4))
 (can_traverse rover2 waypoint1 waypoint5)
 (not (can_traverse rover2 waypoint1 waypoint6))
 (not (can_traverse rover2 waypoint1 waypoint7))
 (not (can_traverse rover2 waypoint1 waypoint8))
 (not (can_traverse rover2 waypoint1 waypoint9))
 (not (can_traverse rover2 waypoint1 waypoint10))
 (not (can_traverse rover2 waypoint1 waypoint11))
 (not (can_traverse rover2 waypoint1 waypoint12))
 (not (can_traverse rover2 waypoint1 waypoint13))
 (can_traverse rover2 waypoint1 waypoint14)
 (can_traverse rover2 waypoint1 waypoint15)
 (not (can_traverse rover2 waypoint1 waypoint16))
 (not (can_traverse rover2 waypoint1 waypoint17))
 (not (can_traverse rover2 waypoint1 waypoint18))
 (not (can_traverse rover2 waypoint1 waypoint19))
 (not (can_traverse rover2 waypoint1 waypoint20))
 (not (can_traverse rover2 waypoint1 waypoint21))
 (not (can_traverse rover2 waypoint1 waypoint22))
 (not (can_traverse rover2 waypoint1 waypoint23))
 (not (can_traverse rover2 waypoint1 waypoint24))
 (not (can_traverse rover2 waypoint2 waypoint0))
 (can_traverse rover2 waypoint2 waypoint1)
 (not (can_traverse rover2 waypoint2 waypoint2))
 (not (can_traverse rover2 waypoint2 waypoint3))
 (not (can_traverse rover2 waypoint2 waypoint4))
 (not (can_traverse rover2 waypoint2 waypoint5))
 (not (can_traverse rover2 waypoint2 waypoint6))
 (not (can_traverse rover2 waypoint2 waypoint7))
 (not (can_traverse rover2 waypoint2 waypoint8))
 (not (can_traverse rover2 waypoint2 waypoint9))
 (not (can_traverse rover2 waypoint2 waypoint10))
 (not (can_traverse rover2 waypoint2 waypoint11))
 (not (can_traverse rover2 waypoint2 waypoint12))
 (not (can_traverse rover2 waypoint2 waypoint13))
 (not (can_traverse rover2 waypoint2 waypoint14))
 (not (can_traverse rover2 waypoint2 waypoint15))
 (not (can_traverse rover2 waypoint2 waypoint16))
 (not (can_traverse rover2 waypoint2 waypoint17))
 (not (can_traverse rover2 waypoint2 waypoint18))
 (not (can_traverse rover2 waypoint2 waypoint19))
 (not (can_traverse rover2 waypoint2 waypoint20))
 (not (can_traverse rover2 waypoint2 waypoint21))
 (not (can_traverse rover2 waypoint2 waypoint22))
 (not (can_traverse rover2 waypoint2 waypoint23))
 (not (can_traverse rover2 waypoint2 waypoint24))
 (not (can_traverse rover2 waypoint3 waypoint0))
 (can_traverse rover2 waypoint3 waypoint1)
 (not (can_traverse rover2 waypoint3 waypoint2))
 (not (can_traverse rover2 waypoint3 waypoint3))
 (not (can_traverse rover2 waypoint3 waypoint4))
 (not (can_traverse rover2 waypoint3 waypoint5))
 (not (can_traverse rover2 waypoint3 waypoint6))
 (not (can_traverse rover2 waypoint3 waypoint7))
 (not (can_traverse rover2 waypoint3 waypoint8))
 (not (can_traverse rover2 waypoint3 waypoint9))
 (not (can_traverse rover2 waypoint3 waypoint10))
 (not (can_traverse rover2 waypoint3 waypoint11))
 (not (can_traverse rover2 waypoint3 waypoint12))
 (can_traverse rover2 waypoint3 waypoint13)
 (not (can_traverse rover2 waypoint3 waypoint14))
 (not (can_traverse rover2 waypoint3 waypoint15))
 (not (can_traverse rover2 waypoint3 waypoint16))
 (not (can_traverse rover2 waypoint3 waypoint17))
 (can_traverse rover2 waypoint3 waypoint18)
 (not (can_traverse rover2 waypoint3 waypoint19))
 (can_traverse rover2 waypoint3 waypoint20)
 (not (can_traverse rover2 waypoint3 waypoint21))
 (not (can_traverse rover2 waypoint3 waypoint22))
 (not (can_traverse rover2 waypoint3 waypoint23))
 (not (can_traverse rover2 waypoint3 waypoint24))
 (not (can_traverse rover2 waypoint4 waypoint0))
 (not (can_traverse rover2 waypoint4 waypoint1))
 (not (can_traverse rover2 waypoint4 waypoint2))
 (not (can_traverse rover2 waypoint4 waypoint3))
 (not (can_traverse rover2 waypoint4 waypoint4))
 (not (can_traverse rover2 waypoint4 waypoint5))
 (not (can_traverse rover2 waypoint4 waypoint6))
 (can_traverse rover2 waypoint4 waypoint7)
 (not (can_traverse rover2 waypoint4 waypoint8))
 (not (can_traverse rover2 waypoint4 waypoint9))
 (not (can_traverse rover2 waypoint4 waypoint10))
 (not (can_traverse rover2 waypoint4 waypoint11))
 (not (can_traverse rover2 waypoint4 waypoint12))
 (can_traverse rover2 waypoint4 waypoint13)
 (not (can_traverse rover2 waypoint4 waypoint14))
 (not (can_traverse rover2 waypoint4 waypoint15))
 (not (can_traverse rover2 waypoint4 waypoint16))
 (not (can_traverse rover2 waypoint4 waypoint17))
 (not (can_traverse rover2 waypoint4 waypoint18))
 (not (can_traverse rover2 waypoint4 waypoint19))
 (not (can_traverse rover2 waypoint4 waypoint20))
 (not (can_traverse rover2 waypoint4 waypoint21))
 (not (can_traverse rover2 waypoint4 waypoint22))
 (not (can_traverse rover2 waypoint4 waypoint23))
 (not (can_traverse rover2 waypoint4 waypoint24))
 (can_traverse rover2 waypoint5 waypoint0)
 (can_traverse rover2 waypoint5 waypoint1)
 (not (can_traverse rover2 waypoint5 waypoint2))
 (not (can_traverse rover2 waypoint5 waypoint3))
 (not (can_traverse rover2 waypoint5 waypoint4))
 (not (can_traverse rover2 waypoint5 waypoint5))
 (not (can_traverse rover2 waypoint5 waypoint6))
 (not (can_traverse rover2 waypoint5 waypoint7))
 (can_traverse rover2 waypoint5 waypoint8)
 (not (can_traverse rover2 waypoint5 waypoint9))
 (not (can_traverse rover2 waypoint5 waypoint10))
 (not (can_traverse rover2 waypoint5 waypoint11))
 (not (can_traverse rover2 waypoint5 waypoint12))
 (not (can_traverse rover2 waypoint5 waypoint13))
 (not (can_traverse rover2 waypoint5 waypoint14))
 (not (can_traverse rover2 waypoint5 waypoint15))
 (not (can_traverse rover2 waypoint5 waypoint16))
 (not (can_traverse rover2 waypoint5 waypoint17))
 (not (can_traverse rover2 waypoint5 waypoint18))
 (not (can_traverse rover2 waypoint5 waypoint19))
 (not (can_traverse rover2 waypoint5 waypoint20))
 (not (can_traverse rover2 waypoint5 waypoint21))
 (not (can_traverse rover2 waypoint5 waypoint22))
 (not (can_traverse rover2 waypoint5 waypoint23))
 (not (can_traverse rover2 waypoint5 waypoint24))
 (not (can_traverse rover2 waypoint6 waypoint0))
 (not (can_traverse rover2 waypoint6 waypoint1))
 (not (can_traverse rover2 waypoint6 waypoint2))
 (not (can_traverse rover2 waypoint6 waypoint3))
 (not (can_traverse rover2 waypoint6 waypoint4))
 (not (can_traverse rover2 waypoint6 waypoint5))
 (not (can_traverse rover2 waypoint6 waypoint6))
 (not (can_traverse rover2 waypoint6 waypoint7))
 (not (can_traverse rover2 waypoint6 waypoint8))
 (not (can_traverse rover2 waypoint6 waypoint9))
 (not (can_traverse rover2 waypoint6 waypoint10))
 (not (can_traverse rover2 waypoint6 waypoint11))
 (not (can_traverse rover2 waypoint6 waypoint12))
 (not (can_traverse rover2 waypoint6 waypoint13))
 (not (can_traverse rover2 waypoint6 waypoint14))
 (not (can_traverse rover2 waypoint6 waypoint15))
 (not (can_traverse rover2 waypoint6 waypoint16))
 (not (can_traverse rover2 waypoint6 waypoint17))
 (can_traverse rover2 waypoint6 waypoint18)
 (not (can_traverse rover2 waypoint6 waypoint19))
 (not (can_traverse rover2 waypoint6 waypoint20))
 (not (can_traverse rover2 waypoint6 waypoint21))
 (not (can_traverse rover2 waypoint6 waypoint22))
 (not (can_traverse rover2 waypoint6 waypoint23))
 (not (can_traverse rover2 waypoint6 waypoint24))
 (not (can_traverse rover2 waypoint7 waypoint0))
 (not (can_traverse rover2 waypoint7 waypoint1))
 (not (can_traverse rover2 waypoint7 waypoint2))
 (not (can_traverse rover2 waypoint7 waypoint3))
 (can_traverse rover2 waypoint7 waypoint4)
 (not (can_traverse rover2 waypoint7 waypoint5))
 (not (can_traverse rover2 waypoint7 waypoint6))
 (not (can_traverse rover2 waypoint7 waypoint7))
 (not (can_traverse rover2 waypoint7 waypoint8))
 (not (can_traverse rover2 waypoint7 waypoint9))
 (not (can_traverse rover2 waypoint7 waypoint10))
 (not (can_traverse rover2 waypoint7 waypoint11))
 (not (can_traverse rover2 waypoint7 waypoint12))
 (not (can_traverse rover2 waypoint7 waypoint13))
 (not (can_traverse rover2 waypoint7 waypoint14))
 (not (can_traverse rover2 waypoint7 waypoint15))
 (not (can_traverse rover2 waypoint7 waypoint16))
 (not (can_traverse rover2 waypoint7 waypoint17))
 (not (can_traverse rover2 waypoint7 waypoint18))
 (not (can_traverse rover2 waypoint7 waypoint19))
 (not (can_traverse rover2 waypoint7 waypoint20))
 (not (can_traverse rover2 waypoint7 waypoint21))
 (not (can_traverse rover2 waypoint7 waypoint22))
 (not (can_traverse rover2 waypoint7 waypoint23))
 (not (can_traverse rover2 waypoint7 waypoint24))
 (not (can_traverse rover2 waypoint8 waypoint0))
 (not (can_traverse rover2 waypoint8 waypoint1))
 (not (can_traverse rover2 waypoint8 waypoint2))
 (not (can_traverse rover2 waypoint8 waypoint3))
 (not (can_traverse rover2 waypoint8 waypoint4))
 (can_traverse rover2 waypoint8 waypoint5)
 (not (can_traverse rover2 waypoint8 waypoint6))
 (not (can_traverse rover2 waypoint8 waypoint7))
 (not (can_traverse rover2 waypoint8 waypoint8))
 (not (can_traverse rover2 waypoint8 waypoint9))
 (not (can_traverse rover2 waypoint8 waypoint10))
 (not (can_traverse rover2 waypoint8 waypoint11))
 (not (can_traverse rover2 waypoint8 waypoint12))
 (not (can_traverse rover2 waypoint8 waypoint13))
 (not (can_traverse rover2 waypoint8 waypoint14))
 (not (can_traverse rover2 waypoint8 waypoint15))
 (not (can_traverse rover2 waypoint8 waypoint16))
 (not (can_traverse rover2 waypoint8 waypoint17))
 (not (can_traverse rover2 waypoint8 waypoint18))
 (not (can_traverse rover2 waypoint8 waypoint19))
 (not (can_traverse rover2 waypoint8 waypoint20))
 (not (can_traverse rover2 waypoint8 waypoint21))
 (not (can_traverse rover2 waypoint8 waypoint22))
 (not (can_traverse rover2 waypoint8 waypoint23))
 (not (can_traverse rover2 waypoint8 waypoint24))
 (not (can_traverse rover2 waypoint9 waypoint0))
 (not (can_traverse rover2 waypoint9 waypoint1))
 (not (can_traverse rover2 waypoint9 waypoint2))
 (not (can_traverse rover2 waypoint9 waypoint3))
 (not (can_traverse rover2 waypoint9 waypoint4))
 (not (can_traverse rover2 waypoint9 waypoint5))
 (not (can_traverse rover2 waypoint9 waypoint6))
 (not (can_traverse rover2 waypoint9 waypoint7))
 (not (can_traverse rover2 waypoint9 waypoint8))
 (not (can_traverse rover2 waypoint9 waypoint9))
 (not (can_traverse rover2 waypoint9 waypoint10))
 (not (can_traverse rover2 waypoint9 waypoint11))
 (not (can_traverse rover2 waypoint9 waypoint12))
 (not (can_traverse rover2 waypoint9 waypoint13))
 (not (can_traverse rover2 waypoint9 waypoint14))
 (not (can_traverse rover2 waypoint9 waypoint15))
 (not (can_traverse rover2 waypoint9 waypoint16))
 (not (can_traverse rover2 waypoint9 waypoint17))
 (can_traverse rover2 waypoint9 waypoint18)
 (not (can_traverse rover2 waypoint9 waypoint19))
 (not (can_traverse rover2 waypoint9 waypoint20))
 (not (can_traverse rover2 waypoint9 waypoint21))
 (not (can_traverse rover2 waypoint9 waypoint22))
 (not (can_traverse rover2 waypoint9 waypoint23))
 (not (can_traverse rover2 waypoint9 waypoint24))
 (not (can_traverse rover2 waypoint10 waypoint0))
 (not (can_traverse rover2 waypoint10 waypoint1))
 (not (can_traverse rover2 waypoint10 waypoint2))
 (not (can_traverse rover2 waypoint10 waypoint3))
 (not (can_traverse rover2 waypoint10 waypoint4))
 (not (can_traverse rover2 waypoint10 waypoint5))
 (not (can_traverse rover2 waypoint10 waypoint6))
 (not (can_traverse rover2 waypoint10 waypoint7))
 (not (can_traverse rover2 waypoint10 waypoint8))
 (not (can_traverse rover2 waypoint10 waypoint9))
 (not (can_traverse rover2 waypoint10 waypoint10))
 (not (can_traverse rover2 waypoint10 waypoint11))
 (not (can_traverse rover2 waypoint10 waypoint12))
 (not (can_traverse rover2 waypoint10 waypoint13))
 (not (can_traverse rover2 waypoint10 waypoint14))
 (can_traverse rover2 waypoint10 waypoint15)
 (not (can_traverse rover2 waypoint10 waypoint16))
 (not (can_traverse rover2 waypoint10 waypoint17))
 (not (can_traverse rover2 waypoint10 waypoint18))
 (not (can_traverse rover2 waypoint10 waypoint19))
 (not (can_traverse rover2 waypoint10 waypoint20))
 (not (can_traverse rover2 waypoint10 waypoint21))
 (not (can_traverse rover2 waypoint10 waypoint22))
 (not (can_traverse rover2 waypoint10 waypoint23))
 (not (can_traverse rover2 waypoint10 waypoint24))
 (not (can_traverse rover2 waypoint11 waypoint0))
 (not (can_traverse rover2 waypoint11 waypoint1))
 (not (can_traverse rover2 waypoint11 waypoint2))
 (not (can_traverse rover2 waypoint11 waypoint3))
 (not (can_traverse rover2 waypoint11 waypoint4))
 (not (can_traverse rover2 waypoint11 waypoint5))
 (not (can_traverse rover2 waypoint11 waypoint6))
 (not (can_traverse rover2 waypoint11 waypoint7))
 (not (can_traverse rover2 waypoint11 waypoint8))
 (not (can_traverse rover2 waypoint11 waypoint9))
 (not (can_traverse rover2 waypoint11 waypoint10))
 (not (can_traverse rover2 waypoint11 waypoint11))
 (not (can_traverse rover2 waypoint11 waypoint12))
 (not (can_traverse rover2 waypoint11 waypoint13))
 (not (can_traverse rover2 waypoint11 waypoint14))
 (not (can_traverse rover2 waypoint11 waypoint15))
 (not (can_traverse rover2 waypoint11 waypoint16))
 (not (can_traverse rover2 waypoint11 waypoint17))
 (not (can_traverse rover2 waypoint11 waypoint18))
 (not (can_traverse rover2 waypoint11 waypoint19))
 (not (can_traverse rover2 waypoint11 waypoint20))
 (can_traverse rover2 waypoint11 waypoint21)
 (not (can_traverse rover2 waypoint11 waypoint22))
 (not (can_traverse rover2 waypoint11 waypoint23))
 (not (can_traverse rover2 waypoint11 waypoint24))
 (not (can_traverse rover2 waypoint12 waypoint0))
 (not (can_traverse rover2 waypoint12 waypoint1))
 (not (can_traverse rover2 waypoint12 waypoint2))
 (not (can_traverse rover2 waypoint12 waypoint3))
 (not (can_traverse rover2 waypoint12 waypoint4))
 (not (can_traverse rover2 waypoint12 waypoint5))
 (not (can_traverse rover2 waypoint12 waypoint6))
 (not (can_traverse rover2 waypoint12 waypoint7))
 (not (can_traverse rover2 waypoint12 waypoint8))
 (not (can_traverse rover2 waypoint12 waypoint9))
 (not (can_traverse rover2 waypoint12 waypoint10))
 (not (can_traverse rover2 waypoint12 waypoint11))
 (not (can_traverse rover2 waypoint12 waypoint12))
 (not (can_traverse rover2 waypoint12 waypoint13))
 (can_traverse rover2 waypoint12 waypoint14)
 (not (can_traverse rover2 waypoint12 waypoint15))
 (not (can_traverse rover2 waypoint12 waypoint16))
 (not (can_traverse rover2 waypoint12 waypoint17))
 (not (can_traverse rover2 waypoint12 waypoint18))
 (not (can_traverse rover2 waypoint12 waypoint19))
 (not (can_traverse rover2 waypoint12 waypoint20))
 (not (can_traverse rover2 waypoint12 waypoint21))
 (not (can_traverse rover2 waypoint12 waypoint22))
 (not (can_traverse rover2 waypoint12 waypoint23))
 (not (can_traverse rover2 waypoint12 waypoint24))
 (not (can_traverse rover2 waypoint13 waypoint0))
 (not (can_traverse rover2 waypoint13 waypoint1))
 (not (can_traverse rover2 waypoint13 waypoint2))
 (can_traverse rover2 waypoint13 waypoint3)
 (can_traverse rover2 waypoint13 waypoint4)
 (not (can_traverse rover2 waypoint13 waypoint5))
 (not (can_traverse rover2 waypoint13 waypoint6))
 (not (can_traverse rover2 waypoint13 waypoint7))
 (not (can_traverse rover2 waypoint13 waypoint8))
 (not (can_traverse rover2 waypoint13 waypoint9))
 (not (can_traverse rover2 waypoint13 waypoint10))
 (not (can_traverse rover2 waypoint13 waypoint11))
 (not (can_traverse rover2 waypoint13 waypoint12))
 (not (can_traverse rover2 waypoint13 waypoint13))
 (not (can_traverse rover2 waypoint13 waypoint14))
 (not (can_traverse rover2 waypoint13 waypoint15))
 (not (can_traverse rover2 waypoint13 waypoint16))
 (not (can_traverse rover2 waypoint13 waypoint17))
 (not (can_traverse rover2 waypoint13 waypoint18))
 (not (can_traverse rover2 waypoint13 waypoint19))
 (not (can_traverse rover2 waypoint13 waypoint20))
 (can_traverse rover2 waypoint13 waypoint21)
 (not (can_traverse rover2 waypoint13 waypoint22))
 (not (can_traverse rover2 waypoint13 waypoint23))
 (not (can_traverse rover2 waypoint13 waypoint24))
 (not (can_traverse rover2 waypoint14 waypoint0))
 (can_traverse rover2 waypoint14 waypoint1)
 (not (can_traverse rover2 waypoint14 waypoint2))
 (not (can_traverse rover2 waypoint14 waypoint3))
 (not (can_traverse rover2 waypoint14 waypoint4))
 (not (can_traverse rover2 waypoint14 waypoint5))
 (not (can_traverse rover2 waypoint14 waypoint6))
 (not (can_traverse rover2 waypoint14 waypoint7))
 (not (can_traverse rover2 waypoint14 waypoint8))
 (not (can_traverse rover2 waypoint14 waypoint9))
 (not (can_traverse rover2 waypoint14 waypoint10))
 (not (can_traverse rover2 waypoint14 waypoint11))
 (can_traverse rover2 waypoint14 waypoint12)
 (not (can_traverse rover2 waypoint14 waypoint13))
 (not (can_traverse rover2 waypoint14 waypoint14))
 (not (can_traverse rover2 waypoint14 waypoint15))
 (not (can_traverse rover2 waypoint14 waypoint16))
 (not (can_traverse rover2 waypoint14 waypoint17))
 (not (can_traverse rover2 waypoint14 waypoint18))
 (not (can_traverse rover2 waypoint14 waypoint19))
 (not (can_traverse rover2 waypoint14 waypoint20))
 (not (can_traverse rover2 waypoint14 waypoint21))
 (not (can_traverse rover2 waypoint14 waypoint22))
 (not (can_traverse rover2 waypoint14 waypoint23))
 (not (can_traverse rover2 waypoint14 waypoint24))
 (not (can_traverse rover2 waypoint15 waypoint0))
 (can_traverse rover2 waypoint15 waypoint1)
 (not (can_traverse rover2 waypoint15 waypoint2))
 (not (can_traverse rover2 waypoint15 waypoint3))
 (not (can_traverse rover2 waypoint15 waypoint4))
 (not (can_traverse rover2 waypoint15 waypoint5))
 (not (can_traverse rover2 waypoint15 waypoint6))
 (not (can_traverse rover2 waypoint15 waypoint7))
 (not (can_traverse rover2 waypoint15 waypoint8))
 (not (can_traverse rover2 waypoint15 waypoint9))
 (can_traverse rover2 waypoint15 waypoint10)
 (not (can_traverse rover2 waypoint15 waypoint11))
 (not (can_traverse rover2 waypoint15 waypoint12))
 (not (can_traverse rover2 waypoint15 waypoint13))
 (not (can_traverse rover2 waypoint15 waypoint14))
 (not (can_traverse rover2 waypoint15 waypoint15))
 (not (can_traverse rover2 waypoint15 waypoint16))
 (not (can_traverse rover2 waypoint15 waypoint17))
 (not (can_traverse rover2 waypoint15 waypoint18))
 (not (can_traverse rover2 waypoint15 waypoint19))
 (not (can_traverse rover2 waypoint15 waypoint20))
 (not (can_traverse rover2 waypoint15 waypoint21))
 (not (can_traverse rover2 waypoint15 waypoint22))
 (not (can_traverse rover2 waypoint15 waypoint23))
 (not (can_traverse rover2 waypoint15 waypoint24))
 (not (can_traverse rover2 waypoint16 waypoint0))
 (not (can_traverse rover2 waypoint16 waypoint1))
 (not (can_traverse rover2 waypoint16 waypoint2))
 (not (can_traverse rover2 waypoint16 waypoint3))
 (not (can_traverse rover2 waypoint16 waypoint4))
 (not (can_traverse rover2 waypoint16 waypoint5))
 (not (can_traverse rover2 waypoint16 waypoint6))
 (not (can_traverse rover2 waypoint16 waypoint7))
 (not (can_traverse rover2 waypoint16 waypoint8))
 (not (can_traverse rover2 waypoint16 waypoint9))
 (not (can_traverse rover2 waypoint16 waypoint10))
 (not (can_traverse rover2 waypoint16 waypoint11))
 (not (can_traverse rover2 waypoint16 waypoint12))
 (not (can_traverse rover2 waypoint16 waypoint13))
 (not (can_traverse rover2 waypoint16 waypoint14))
 (not (can_traverse rover2 waypoint16 waypoint15))
 (not (can_traverse rover2 waypoint16 waypoint16))
 (not (can_traverse rover2 waypoint16 waypoint17))
 (not (can_traverse rover2 waypoint16 waypoint18))
 (not (can_traverse rover2 waypoint16 waypoint19))
 (can_traverse rover2 waypoint16 waypoint20)
 (not (can_traverse rover2 waypoint16 waypoint21))
 (not (can_traverse rover2 waypoint16 waypoint22))
 (not (can_traverse rover2 waypoint16 waypoint23))
 (not (can_traverse rover2 waypoint16 waypoint24))
 (not (can_traverse rover2 waypoint17 waypoint0))
 (not (can_traverse rover2 waypoint17 waypoint1))
 (not (can_traverse rover2 waypoint17 waypoint2))
 (not (can_traverse rover2 waypoint17 waypoint3))
 (not (can_traverse rover2 waypoint17 waypoint4))
 (not (can_traverse rover2 waypoint17 waypoint5))
 (not (can_traverse rover2 waypoint17 waypoint6))
 (not (can_traverse rover2 waypoint17 waypoint7))
 (not (can_traverse rover2 waypoint17 waypoint8))
 (not (can_traverse rover2 waypoint17 waypoint9))
 (not (can_traverse rover2 waypoint17 waypoint10))
 (not (can_traverse rover2 waypoint17 waypoint11))
 (not (can_traverse rover2 waypoint17 waypoint12))
 (not (can_traverse rover2 waypoint17 waypoint13))
 (not (can_traverse rover2 waypoint17 waypoint14))
 (not (can_traverse rover2 waypoint17 waypoint15))
 (not (can_traverse rover2 waypoint17 waypoint16))
 (not (can_traverse rover2 waypoint17 waypoint17))
 (can_traverse rover2 waypoint17 waypoint18)
 (not (can_traverse rover2 waypoint17 waypoint19))
 (not (can_traverse rover2 waypoint17 waypoint20))
 (not (can_traverse rover2 waypoint17 waypoint21))
 (not (can_traverse rover2 waypoint17 waypoint22))
 (not (can_traverse rover2 waypoint17 waypoint23))
 (not (can_traverse rover2 waypoint17 waypoint24))
 (not (can_traverse rover2 waypoint18 waypoint0))
 (not (can_traverse rover2 waypoint18 waypoint1))
 (not (can_traverse rover2 waypoint18 waypoint2))
 (can_traverse rover2 waypoint18 waypoint3)
 (not (can_traverse rover2 waypoint18 waypoint4))
 (not (can_traverse rover2 waypoint18 waypoint5))
 (can_traverse rover2 waypoint18 waypoint6)
 (not (can_traverse rover2 waypoint18 waypoint7))
 (not (can_traverse rover2 waypoint18 waypoint8))
 (can_traverse rover2 waypoint18 waypoint9)
 (not (can_traverse rover2 waypoint18 waypoint10))
 (not (can_traverse rover2 waypoint18 waypoint11))
 (not (can_traverse rover2 waypoint18 waypoint12))
 (not (can_traverse rover2 waypoint18 waypoint13))
 (not (can_traverse rover2 waypoint18 waypoint14))
 (not (can_traverse rover2 waypoint18 waypoint15))
 (not (can_traverse rover2 waypoint18 waypoint16))
 (can_traverse rover2 waypoint18 waypoint17)
 (not (can_traverse rover2 waypoint18 waypoint18))
 (not (can_traverse rover2 waypoint18 waypoint19))
 (not (can_traverse rover2 waypoint18 waypoint20))
 (not (can_traverse rover2 waypoint18 waypoint21))
 (not (can_traverse rover2 waypoint18 waypoint22))
 (can_traverse rover2 waypoint18 waypoint23)
 (can_traverse rover2 waypoint18 waypoint24)
 (not (can_traverse rover2 waypoint19 waypoint0))
 (not (can_traverse rover2 waypoint19 waypoint1))
 (not (can_traverse rover2 waypoint19 waypoint2))
 (not (can_traverse rover2 waypoint19 waypoint3))
 (not (can_traverse rover2 waypoint19 waypoint4))
 (not (can_traverse rover2 waypoint19 waypoint5))
 (not (can_traverse rover2 waypoint19 waypoint6))
 (not (can_traverse rover2 waypoint19 waypoint7))
 (not (can_traverse rover2 waypoint19 waypoint8))
 (not (can_traverse rover2 waypoint19 waypoint9))
 (not (can_traverse rover2 waypoint19 waypoint10))
 (not (can_traverse rover2 waypoint19 waypoint11))
 (not (can_traverse rover2 waypoint19 waypoint12))
 (not (can_traverse rover2 waypoint19 waypoint13))
 (not (can_traverse rover2 waypoint19 waypoint14))
 (not (can_traverse rover2 waypoint19 waypoint15))
 (not (can_traverse rover2 waypoint19 waypoint16))
 (not (can_traverse rover2 waypoint19 waypoint17))
 (not (can_traverse rover2 waypoint19 waypoint18))
 (not (can_traverse rover2 waypoint19 waypoint19))
 (can_traverse rover2 waypoint19 waypoint20)
 (not (can_traverse rover2 waypoint19 waypoint21))
 (not (can_traverse rover2 waypoint19 waypoint22))
 (not (can_traverse rover2 waypoint19 waypoint23))
 (not (can_traverse rover2 waypoint19 waypoint24))
 (not (can_traverse rover2 waypoint20 waypoint0))
 (not (can_traverse rover2 waypoint20 waypoint1))
 (not (can_traverse rover2 waypoint20 waypoint2))
 (can_traverse rover2 waypoint20 waypoint3)
 (not (can_traverse rover2 waypoint20 waypoint4))
 (not (can_traverse rover2 waypoint20 waypoint5))
 (not (can_traverse rover2 waypoint20 waypoint6))
 (not (can_traverse rover2 waypoint20 waypoint7))
 (not (can_traverse rover2 waypoint20 waypoint8))
 (not (can_traverse rover2 waypoint20 waypoint9))
 (not (can_traverse rover2 waypoint20 waypoint10))
 (not (can_traverse rover2 waypoint20 waypoint11))
 (not (can_traverse rover2 waypoint20 waypoint12))
 (not (can_traverse rover2 waypoint20 waypoint13))
 (not (can_traverse rover2 waypoint20 waypoint14))
 (not (can_traverse rover2 waypoint20 waypoint15))
 (can_traverse rover2 waypoint20 waypoint16)
 (not (can_traverse rover2 waypoint20 waypoint17))
 (not (can_traverse rover2 waypoint20 waypoint18))
 (can_traverse rover2 waypoint20 waypoint19)
 (not (can_traverse rover2 waypoint20 waypoint20))
 (not (can_traverse rover2 waypoint20 waypoint21))
 (not (can_traverse rover2 waypoint20 waypoint22))
 (not (can_traverse rover2 waypoint20 waypoint23))
 (not (can_traverse rover2 waypoint20 waypoint24))
 (not (can_traverse rover2 waypoint21 waypoint0))
 (not (can_traverse rover2 waypoint21 waypoint1))
 (not (can_traverse rover2 waypoint21 waypoint2))
 (not (can_traverse rover2 waypoint21 waypoint3))
 (not (can_traverse rover2 waypoint21 waypoint4))
 (not (can_traverse rover2 waypoint21 waypoint5))
 (not (can_traverse rover2 waypoint21 waypoint6))
 (not (can_traverse rover2 waypoint21 waypoint7))
 (not (can_traverse rover2 waypoint21 waypoint8))
 (not (can_traverse rover2 waypoint21 waypoint9))
 (not (can_traverse rover2 waypoint21 waypoint10))
 (can_traverse rover2 waypoint21 waypoint11)
 (not (can_traverse rover2 waypoint21 waypoint12))
 (can_traverse rover2 waypoint21 waypoint13)
 (not (can_traverse rover2 waypoint21 waypoint14))
 (not (can_traverse rover2 waypoint21 waypoint15))
 (not (can_traverse rover2 waypoint21 waypoint16))
 (not (can_traverse rover2 waypoint21 waypoint17))
 (not (can_traverse rover2 waypoint21 waypoint18))
 (not (can_traverse rover2 waypoint21 waypoint19))
 (not (can_traverse rover2 waypoint21 waypoint20))
 (not (can_traverse rover2 waypoint21 waypoint21))
 (can_traverse rover2 waypoint21 waypoint22)
 (not (can_traverse rover2 waypoint21 waypoint23))
 (not (can_traverse rover2 waypoint21 waypoint24))
 (not (can_traverse rover2 waypoint22 waypoint0))
 (not (can_traverse rover2 waypoint22 waypoint1))
 (not (can_traverse rover2 waypoint22 waypoint2))
 (not (can_traverse rover2 waypoint22 waypoint3))
 (not (can_traverse rover2 waypoint22 waypoint4))
 (not (can_traverse rover2 waypoint22 waypoint5))
 (not (can_traverse rover2 waypoint22 waypoint6))
 (not (can_traverse rover2 waypoint22 waypoint7))
 (not (can_traverse rover2 waypoint22 waypoint8))
 (not (can_traverse rover2 waypoint22 waypoint9))
 (not (can_traverse rover2 waypoint22 waypoint10))
 (not (can_traverse rover2 waypoint22 waypoint11))
 (not (can_traverse rover2 waypoint22 waypoint12))
 (not (can_traverse rover2 waypoint22 waypoint13))
 (not (can_traverse rover2 waypoint22 waypoint14))
 (not (can_traverse rover2 waypoint22 waypoint15))
 (not (can_traverse rover2 waypoint22 waypoint16))
 (not (can_traverse rover2 waypoint22 waypoint17))
 (not (can_traverse rover2 waypoint22 waypoint18))
 (not (can_traverse rover2 waypoint22 waypoint19))
 (not (can_traverse rover2 waypoint22 waypoint20))
 (can_traverse rover2 waypoint22 waypoint21)
 (not (can_traverse rover2 waypoint22 waypoint22))
 (not (can_traverse rover2 waypoint22 waypoint23))
 (not (can_traverse rover2 waypoint22 waypoint24))
 (not (can_traverse rover2 waypoint23 waypoint0))
 (not (can_traverse rover2 waypoint23 waypoint1))
 (not (can_traverse rover2 waypoint23 waypoint2))
 (not (can_traverse rover2 waypoint23 waypoint3))
 (not (can_traverse rover2 waypoint23 waypoint4))
 (not (can_traverse rover2 waypoint23 waypoint5))
 (not (can_traverse rover2 waypoint23 waypoint6))
 (not (can_traverse rover2 waypoint23 waypoint7))
 (not (can_traverse rover2 waypoint23 waypoint8))
 (not (can_traverse rover2 waypoint23 waypoint9))
 (not (can_traverse rover2 waypoint23 waypoint10))
 (not (can_traverse rover2 waypoint23 waypoint11))
 (not (can_traverse rover2 waypoint23 waypoint12))
 (not (can_traverse rover2 waypoint23 waypoint13))
 (not (can_traverse rover2 waypoint23 waypoint14))
 (not (can_traverse rover2 waypoint23 waypoint15))
 (not (can_traverse rover2 waypoint23 waypoint16))
 (not (can_traverse rover2 waypoint23 waypoint17))
 (can_traverse rover2 waypoint23 waypoint18)
 (not (can_traverse rover2 waypoint23 waypoint19))
 (not (can_traverse rover2 waypoint23 waypoint20))
 (not (can_traverse rover2 waypoint23 waypoint21))
 (not (can_traverse rover2 waypoint23 waypoint22))
 (not (can_traverse rover2 waypoint23 waypoint23))
 (not (can_traverse rover2 waypoint23 waypoint24))
 (not (can_traverse rover2 waypoint24 waypoint0))
 (not (can_traverse rover2 waypoint24 waypoint1))
 (not (can_traverse rover2 waypoint24 waypoint2))
 (not (can_traverse rover2 waypoint24 waypoint3))
 (not (can_traverse rover2 waypoint24 waypoint4))
 (not (can_traverse rover2 waypoint24 waypoint5))
 (not (can_traverse rover2 waypoint24 waypoint6))
 (not (can_traverse rover2 waypoint24 waypoint7))
 (not (can_traverse rover2 waypoint24 waypoint8))
 (not (can_traverse rover2 waypoint24 waypoint9))
 (not (can_traverse rover2 waypoint24 waypoint10))
 (not (can_traverse rover2 waypoint24 waypoint11))
 (not (can_traverse rover2 waypoint24 waypoint12))
 (not (can_traverse rover2 waypoint24 waypoint13))
 (not (can_traverse rover2 waypoint24 waypoint14))
 (not (can_traverse rover2 waypoint24 waypoint15))
 (not (can_traverse rover2 waypoint24 waypoint16))
 (not (can_traverse rover2 waypoint24 waypoint17))
 (can_traverse rover2 waypoint24 waypoint18)
 (not (can_traverse rover2 waypoint24 waypoint19))
 (not (can_traverse rover2 waypoint24 waypoint20))
 (not (can_traverse rover2 waypoint24 waypoint21))
 (not (can_traverse rover2 waypoint24 waypoint22))
 (not (can_traverse rover2 waypoint24 waypoint23))
 (not (can_traverse rover2 waypoint24 waypoint24))
 (not (have_rock_analysis rover2 waypoint0))
 (not (have_rock_analysis rover2 waypoint1))
 (not (have_rock_analysis rover2 waypoint2))
 (not (have_rock_analysis rover2 waypoint3))
 (not (have_rock_analysis rover2 waypoint4))
 (not (have_rock_analysis rover2 waypoint5))
 (not (have_rock_analysis rover2 waypoint6))
 (not (have_rock_analysis rover2 waypoint7))
 (not (have_rock_analysis rover2 waypoint8))
 (not (have_rock_analysis rover2 waypoint9))
 (not (have_rock_analysis rover2 waypoint10))
 (not (have_rock_analysis rover2 waypoint11))
 (not (have_rock_analysis rover2 waypoint12))
 (not (have_rock_analysis rover2 waypoint13))
 (not (have_rock_analysis rover2 waypoint14))
 (not (have_rock_analysis rover2 waypoint15))
 (not (have_rock_analysis rover2 waypoint16))
 (not (have_rock_analysis rover2 waypoint17))
 (not (have_rock_analysis rover2 waypoint18))
 (not (have_rock_analysis rover2 waypoint19))
 (not (have_rock_analysis rover2 waypoint20))
 (not (have_rock_analysis rover2 waypoint21))
 (not (have_rock_analysis rover2 waypoint22))
 (not (have_rock_analysis rover2 waypoint23))
 (not (have_rock_analysis rover2 waypoint24))
 (not (have_soil_analysis rover2 waypoint0))
 (not (have_soil_analysis rover2 waypoint1))
 (not (have_soil_analysis rover2 waypoint2))
 (not (have_soil_analysis rover2 waypoint3))
 (not (have_soil_analysis rover2 waypoint4))
 (not (have_soil_analysis rover2 waypoint5))
 (not (have_soil_analysis rover2 waypoint6))
 (not (have_soil_analysis rover2 waypoint7))
 (not (have_soil_analysis rover2 waypoint8))
 (not (have_soil_analysis rover2 waypoint9))
 (not (have_soil_analysis rover2 waypoint10))
 (not (have_soil_analysis rover2 waypoint11))
 (not (have_soil_analysis rover2 waypoint12))
 (not (have_soil_analysis rover2 waypoint13))
 (not (have_soil_analysis rover2 waypoint14))
 (not (have_soil_analysis rover2 waypoint15))
 (not (have_soil_analysis rover2 waypoint16))
 (not (have_soil_analysis rover2 waypoint17))
 (not (have_soil_analysis rover2 waypoint18))
 (not (have_soil_analysis rover2 waypoint19))
 (not (have_soil_analysis rover2 waypoint20))
 (not (have_soil_analysis rover2 waypoint21))
 (not (have_soil_analysis rover2 waypoint22))
 (not (have_soil_analysis rover2 waypoint23))
 (not (have_soil_analysis rover2 waypoint24))
 (not (visible waypoint0 waypoint0))
 (not (visible waypoint0 waypoint1))
 (not (visible waypoint0 waypoint2))
 (not (visible waypoint0 waypoint3))
 (not (visible waypoint0 waypoint4))
 (visible waypoint0 waypoint5)
 (not (visible waypoint0 waypoint6))
 (visible waypoint0 waypoint7)
 (not (visible waypoint0 waypoint8))
 (not (visible waypoint0 waypoint9))
 (not (visible waypoint0 waypoint10))
 (not (visible waypoint0 waypoint11))
 (not (visible waypoint0 waypoint12))
 (not (visible waypoint0 waypoint13))
 (visible waypoint0 waypoint14)
 (visible waypoint0 waypoint15)
 (not (visible waypoint0 waypoint16))
 (not (visible waypoint0 waypoint17))
 (visible waypoint0 waypoint18)
 (not (visible waypoint0 waypoint19))
 (not (visible waypoint0 waypoint20))
 (not (visible waypoint0 waypoint21))
 (not (visible waypoint0 waypoint22))
 (visible waypoint0 waypoint23)
 (not (visible waypoint0 waypoint24))
 (not (visible waypoint1 waypoint0))
 (not (visible waypoint1 waypoint1))
 (visible waypoint1 waypoint2)
 (visible waypoint1 waypoint3)
 (visible waypoint1 waypoint4)
 (visible waypoint1 waypoint5)
 (not (visible waypoint1 waypoint6))
 (not (visible waypoint1 waypoint7))
 (not (visible waypoint1 waypoint8))
 (not (visible waypoint1 waypoint9))
 (not (visible waypoint1 waypoint10))
 (not (visible waypoint1 waypoint11))
 (not (visible waypoint1 waypoint12))
 (not (visible waypoint1 waypoint13))
 (visible waypoint1 waypoint14)
 (visible waypoint1 waypoint15)
 (not (visible waypoint1 waypoint16))
 (not (visible waypoint1 waypoint17))
 (visible waypoint1 waypoint18)
 (not (visible waypoint1 waypoint19))
 (not (visible waypoint1 waypoint20))
 (not (visible waypoint1 waypoint21))
 (not (visible waypoint1 waypoint22))
 (visible waypoint1 waypoint23)
 (not (visible waypoint1 waypoint24))
 (not (visible waypoint2 waypoint0))
 (visible waypoint2 waypoint1)
 (not (visible waypoint2 waypoint2))
 (not (visible waypoint2 waypoint3))
 (not (visible waypoint2 waypoint4))
 (visible waypoint2 waypoint5)
 (visible waypoint2 waypoint6)
 (not (visible waypoint2 waypoint7))
 (not (visible waypoint2 waypoint8))
 (visible waypoint2 waypoint9)
 (not (visible waypoint2 waypoint10))
 (not (visible waypoint2 waypoint11))
 (not (visible waypoint2 waypoint12))
 (not (visible waypoint2 waypoint13))
 (visible waypoint2 waypoint14)
 (not (visible waypoint2 waypoint15))
 (visible waypoint2 waypoint16)
 (not (visible waypoint2 waypoint17))
 (not (visible waypoint2 waypoint18))
 (not (visible waypoint2 waypoint19))
 (not (visible waypoint2 waypoint20))
 (not (visible waypoint2 waypoint21))
 (not (visible waypoint2 waypoint22))
 (visible waypoint2 waypoint23)
 (not (visible waypoint2 waypoint24))
 (not (visible waypoint3 waypoint0))
 (visible waypoint3 waypoint1)
 (not (visible waypoint3 waypoint2))
 (not (visible waypoint3 waypoint3))
 (not (visible waypoint3 waypoint4))
 (not (visible waypoint3 waypoint5))
 (not (visible waypoint3 waypoint6))
 (not (visible waypoint3 waypoint7))
 (not (visible waypoint3 waypoint8))
 (not (visible waypoint3 waypoint9))
 (not (visible waypoint3 waypoint10))
 (not (visible waypoint3 waypoint11))
 (visible waypoint3 waypoint12)
 (visible waypoint3 waypoint13)
 (not (visible waypoint3 waypoint14))
 (visible waypoint3 waypoint15)
 (not (visible waypoint3 waypoint16))
 (not (visible waypoint3 waypoint17))
 (visible waypoint3 waypoint18)
 (not (visible waypoint3 waypoint19))
 (visible waypoint3 waypoint20)
 (not (visible waypoint3 waypoint21))
 (not (visible waypoint3 waypoint22))
 (not (visible waypoint3 waypoint23))
 (not (visible waypoint3 waypoint24))
 (not (visible waypoint4 waypoint0))
 (visible waypoint4 waypoint1)
 (not (visible waypoint4 waypoint2))
 (not (visible waypoint4 waypoint3))
 (not (visible waypoint4 waypoint4))
 (visible waypoint4 waypoint5)
 (visible waypoint4 waypoint6)
 (visible waypoint4 waypoint7)
 (visible waypoint4 waypoint8)
 (not (visible waypoint4 waypoint9))
 (not (visible waypoint4 waypoint10))
 (not (visible waypoint4 waypoint11))
 (not (visible waypoint4 waypoint12))
 (visible waypoint4 waypoint13)
 (not (visible waypoint4 waypoint14))
 (not (visible waypoint4 waypoint15))
 (visible waypoint4 waypoint16)
 (not (visible waypoint4 waypoint17))
 (not (visible waypoint4 waypoint18))
 (visible waypoint4 waypoint19)
 (visible waypoint4 waypoint20)
 (visible waypoint4 waypoint21)
 (not (visible waypoint4 waypoint22))
 (not (visible waypoint4 waypoint23))
 (not (visible waypoint4 waypoint24))
 (visible waypoint5 waypoint0)
 (visible waypoint5 waypoint1)
 (visible waypoint5 waypoint2)
 (not (visible waypoint5 waypoint3))
 (visible waypoint5 waypoint4)
 (not (visible waypoint5 waypoint5))
 (visible waypoint5 waypoint6)
 (not (visible waypoint5 waypoint7))
 (visible waypoint5 waypoint8)
 (visible waypoint5 waypoint9)
 (not (visible waypoint5 waypoint10))
 (not (visible waypoint5 waypoint11))
 (not (visible waypoint5 waypoint12))
 (not (visible waypoint5 waypoint13))
 (visible waypoint5 waypoint14)
 (not (visible waypoint5 waypoint15))
 (visible waypoint5 waypoint16)
 (not (visible waypoint5 waypoint17))
 (not (visible waypoint5 waypoint18))
 (not (visible waypoint5 waypoint19))
 (not (visible waypoint5 waypoint20))
 (visible waypoint5 waypoint21)
 (not (visible waypoint5 waypoint22))
 (not (visible waypoint5 waypoint23))
 (visible waypoint5 waypoint24)
 (not (visible waypoint6 waypoint0))
 (not (visible waypoint6 waypoint1))
 (visible waypoint6 waypoint2)
 (not (visible waypoint6 waypoint3))
 (visible waypoint6 waypoint4)
 (visible waypoint6 waypoint5)
 (not (visible waypoint6 waypoint6))
 (not (visible waypoint6 waypoint7))
 (visible waypoint6 waypoint8)
 (visible waypoint6 waypoint9)
 (not (visible waypoint6 waypoint10))
 (visible waypoint6 waypoint11)
 (visible waypoint6 waypoint12)
 (not (visible waypoint6 waypoint13))
 (visible waypoint6 waypoint14)
 (visible waypoint6 waypoint15)
 (not (visible waypoint6 waypoint16))
 (not (visible waypoint6 waypoint17))
 (visible waypoint6 waypoint18)
 (visible waypoint6 waypoint19)
 (not (visible waypoint6 waypoint20))
 (visible waypoint6 waypoint21)
 (not (visible waypoint6 waypoint22))
 (not (visible waypoint6 waypoint23))
 (not (visible waypoint6 waypoint24))
 (visible waypoint7 waypoint0)
 (not (visible waypoint7 waypoint1))
 (not (visible waypoint7 waypoint2))
 (not (visible waypoint7 waypoint3))
 (visible waypoint7 waypoint4)
 (not (visible waypoint7 waypoint5))
 (not (visible waypoint7 waypoint6))
 (not (visible waypoint7 waypoint7))
 (visible waypoint7 waypoint8)
 (visible waypoint7 waypoint9)
 (not (visible waypoint7 waypoint10))
 (not (visible waypoint7 waypoint11))
 (not (visible waypoint7 waypoint12))
 (not (visible waypoint7 waypoint13))
 (not (visible waypoint7 waypoint14))
 (not (visible waypoint7 waypoint15))
 (visible waypoint7 waypoint16)
 (visible waypoint7 waypoint17)
 (not (visible waypoint7 waypoint18))
 (not (visible waypoint7 waypoint19))
 (not (visible waypoint7 waypoint20))
 (not (visible waypoint7 waypoint21))
 (not (visible waypoint7 waypoint22))
 (not (visible waypoint7 waypoint23))
 (visible waypoint7 waypoint24)
 (not (visible waypoint8 waypoint0))
 (not (visible waypoint8 waypoint1))
 (not (visible waypoint8 waypoint2))
 (not (visible waypoint8 waypoint3))
 (visible waypoint8 waypoint4)
 (visible waypoint8 waypoint5)
 (visible waypoint8 waypoint6)
 (visible waypoint8 waypoint7)
 (not (visible waypoint8 waypoint8))
 (not (visible waypoint8 waypoint9))
 (not (visible waypoint8 waypoint10))
 (visible waypoint8 waypoint11)
 (not (visible waypoint8 waypoint12))
 (not (visible waypoint8 waypoint13))
 (visible waypoint8 waypoint14)
 (not (visible waypoint8 waypoint15))
 (visible waypoint8 waypoint16)
 (visible waypoint8 waypoint17)
 (visible waypoint8 waypoint18)
 (not (visible waypoint8 waypoint19))
 (not (visible waypoint8 waypoint20))
 (visible waypoint8 waypoint21)
 (not (visible waypoint8 waypoint22))
 (not (visible waypoint8 waypoint23))
 (not (visible waypoint8 waypoint24))
 (not (visible waypoint9 waypoint0))
 (not (visible waypoint9 waypoint1))
 (visible waypoint9 waypoint2)
 (not (visible waypoint9 waypoint3))
 (not (visible waypoint9 waypoint4))
 (visible waypoint9 waypoint5)
 (visible waypoint9 waypoint6)
 (visible waypoint9 waypoint7)
 (not (visible waypoint9 waypoint8))
 (not (visible waypoint9 waypoint9))
 (not (visible waypoint9 waypoint10))
 (not (visible waypoint9 waypoint11))
 (not (visible waypoint9 waypoint12))
 (not (visible waypoint9 waypoint13))
 (visible waypoint9 waypoint14)
 (not (visible waypoint9 waypoint15))
 (not (visible waypoint9 waypoint16))
 (visible waypoint9 waypoint17)
 (visible waypoint9 waypoint18)
 (not (visible waypoint9 waypoint19))
 (not (visible waypoint9 waypoint20))
 (not (visible waypoint9 waypoint21))
 (not (visible waypoint9 waypoint22))
 (not (visible waypoint9 waypoint23))
 (not (visible waypoint9 waypoint24))
 (not (visible waypoint10 waypoint0))
 (not (visible waypoint10 waypoint1))
 (not (visible waypoint10 waypoint2))
 (not (visible waypoint10 waypoint3))
 (not (visible waypoint10 waypoint4))
 (not (visible waypoint10 waypoint5))
 (not (visible waypoint10 waypoint6))
 (not (visible waypoint10 waypoint7))
 (not (visible waypoint10 waypoint8))
 (not (visible waypoint10 waypoint9))
 (not (visible waypoint10 waypoint10))
 (visible waypoint10 waypoint11)
 (not (visible waypoint10 waypoint12))
 (not (visible waypoint10 waypoint13))
 (not (visible waypoint10 waypoint14))
 (visible waypoint10 waypoint15)
 (visible waypoint10 waypoint16)
 (not (visible waypoint10 waypoint17))
 (visible waypoint10 waypoint18)
 (not (visible waypoint10 waypoint19))
 (not (visible waypoint10 waypoint20))
 (not (visible waypoint10 waypoint21))
 (not (visible waypoint10 waypoint22))
 (visible waypoint10 waypoint23)
 (not (visible waypoint10 waypoint24))
 (not (visible waypoint11 waypoint0))
 (not (visible waypoint11 waypoint1))
 (not (visible waypoint11 waypoint2))
 (not (visible waypoint11 waypoint3))
 (not (visible waypoint11 waypoint4))
 (not (visible waypoint11 waypoint5))
 (visible waypoint11 waypoint6)
 (not (visible waypoint11 waypoint7))
 (visible waypoint11 waypoint8)
 (not (visible waypoint11 waypoint9))
 (visible waypoint11 waypoint10)
 (not (visible waypoint11 waypoint11))
 (visible waypoint11 waypoint12)
 (not (visible waypoint11 waypoint13))
 (not (visible waypoint11 waypoint14))
 (not (visible waypoint11 waypoint15))
 (not (visible waypoint11 waypoint16))
 (visible waypoint11 waypoint17)
 (not (visible waypoint11 waypoint18))
 (visible waypoint11 waypoint19)
 (not (visible waypoint11 waypoint20))
 (visible waypoint11 waypoint21)
 (visible waypoint11 waypoint22)
 (not (visible waypoint11 waypoint23))
 (not (visible waypoint11 waypoint24))
 (not (visible waypoint12 waypoint0))
 (not (visible waypoint12 waypoint1))
 (not (visible waypoint12 waypoint2))
 (visible waypoint12 waypoint3)
 (not (visible waypoint12 waypoint4))
 (not (visible waypoint12 waypoint5))
 (visible waypoint12 waypoint6)
 (not (visible waypoint12 waypoint7))
 (not (visible waypoint12 waypoint8))
 (not (visible waypoint12 waypoint9))
 (not (visible waypoint12 waypoint10))
 (visible waypoint12 waypoint11)
 (not (visible waypoint12 waypoint12))
 (visible waypoint12 waypoint13)
 (visible waypoint12 waypoint14)
 (visible waypoint12 waypoint15)
 (not (visible waypoint12 waypoint16))
 (not (visible waypoint12 waypoint17))
 (not (visible waypoint12 waypoint18))
 (visible waypoint12 waypoint19)
 (not (visible waypoint12 waypoint20))
 (not (visible waypoint12 waypoint21))
 (visible waypoint12 waypoint22)
 (visible waypoint12 waypoint23)
 (visible waypoint12 waypoint24)
 (not (visible waypoint13 waypoint0))
 (not (visible waypoint13 waypoint1))
 (not (visible waypoint13 waypoint2))
 (visible waypoint13 waypoint3)
 (visible waypoint13 waypoint4)
 (not (visible waypoint13 waypoint5))
 (not (visible waypoint13 waypoint6))
 (not (visible waypoint13 waypoint7))
 (not (visible waypoint13 waypoint8))
 (not (visible waypoint13 waypoint9))
 (not (visible waypoint13 waypoint10))
 (not (visible waypoint13 waypoint11))
 (visible waypoint13 waypoint12)
 (not (visible waypoint13 waypoint13))
 (visible waypoint13 waypoint14)
 (visible waypoint13 waypoint15)
 (not (visible waypoint13 waypoint16))
 (not (visible waypoint13 waypoint17))
 (not (visible waypoint13 waypoint18))
 (not (visible waypoint13 waypoint19))
 (visible waypoint13 waypoint20)
 (visible waypoint13 waypoint21)
 (not (visible waypoint13 waypoint22))
 (not (visible waypoint13 waypoint23))
 (not (visible waypoint13 waypoint24))
 (visible waypoint14 waypoint0)
 (visible waypoint14 waypoint1)
 (visible waypoint14 waypoint2)
 (not (visible waypoint14 waypoint3))
 (not (visible waypoint14 waypoint4))
 (visible waypoint14 waypoint5)
 (visible waypoint14 waypoint6)
 (not (visible waypoint14 waypoint7))
 (visible waypoint14 waypoint8)
 (visible waypoint14 waypoint9)
 (not (visible waypoint14 waypoint10))
 (not (visible waypoint14 waypoint11))
 (visible waypoint14 waypoint12)
 (visible waypoint14 waypoint13)
 (not (visible waypoint14 waypoint14))
 (not (visible waypoint14 waypoint15))
 (not (visible waypoint14 waypoint16))
 (visible waypoint14 waypoint17)
 (not (visible waypoint14 waypoint18))
 (not (visible waypoint14 waypoint19))
 (visible waypoint14 waypoint20)
 (not (visible waypoint14 waypoint21))
 (not (visible waypoint14 waypoint22))
 (not (visible waypoint14 waypoint23))
 (not (visible waypoint14 waypoint24))
 (visible waypoint15 waypoint0)
 (visible waypoint15 waypoint1)
 (not (visible waypoint15 waypoint2))
 (visible waypoint15 waypoint3)
 (not (visible waypoint15 waypoint4))
 (not (visible waypoint15 waypoint5))
 (visible waypoint15 waypoint6)
 (not (visible waypoint15 waypoint7))
 (not (visible waypoint15 waypoint8))
 (not (visible waypoint15 waypoint9))
 (visible waypoint15 waypoint10)
 (not (visible waypoint15 waypoint11))
 (visible waypoint15 waypoint12)
 (visible waypoint15 waypoint13)
 (not (visible waypoint15 waypoint14))
 (not (visible waypoint15 waypoint15))
 (visible waypoint15 waypoint16)
 (visible waypoint15 waypoint17)
 (not (visible waypoint15 waypoint18))
 (not (visible waypoint15 waypoint19))
 (not (visible waypoint15 waypoint20))
 (not (visible waypoint15 waypoint21))
 (not (visible waypoint15 waypoint22))
 (not (visible waypoint15 waypoint23))
 (not (visible waypoint15 waypoint24))
 (not (visible waypoint16 waypoint0))
 (not (visible waypoint16 waypoint1))
 (visible waypoint16 waypoint2)
 (not (visible waypoint16 waypoint3))
 (visible waypoint16 waypoint4)
 (visible waypoint16 waypoint5)
 (not (visible waypoint16 waypoint6))
 (visible waypoint16 waypoint7)
 (visible waypoint16 waypoint8)
 (not (visible waypoint16 waypoint9))
 (visible waypoint16 waypoint10)
 (not (visible waypoint16 waypoint11))
 (not (visible waypoint16 waypoint12))
 (not (visible waypoint16 waypoint13))
 (not (visible waypoint16 waypoint14))
 (visible waypoint16 waypoint15)
 (not (visible waypoint16 waypoint16))
 (not (visible waypoint16 waypoint17))
 (not (visible waypoint16 waypoint18))
 (not (visible waypoint16 waypoint19))
 (visible waypoint16 waypoint20)
 (not (visible waypoint16 waypoint21))
 (visible waypoint16 waypoint22)
 (not (visible waypoint16 waypoint23))
 (not (visible waypoint16 waypoint24))
 (not (visible waypoint17 waypoint0))
 (not (visible waypoint17 waypoint1))
 (not (visible waypoint17 waypoint2))
 (not (visible waypoint17 waypoint3))
 (not (visible waypoint17 waypoint4))
 (not (visible waypoint17 waypoint5))
 (not (visible waypoint17 waypoint6))
 (visible waypoint17 waypoint7)
 (visible waypoint17 waypoint8)
 (visible waypoint17 waypoint9)
 (not (visible waypoint17 waypoint10))
 (visible waypoint17 waypoint11)
 (not (visible waypoint17 waypoint12))
 (not (visible waypoint17 waypoint13))
 (visible waypoint17 waypoint14)
 (visible waypoint17 waypoint15)
 (not (visible waypoint17 waypoint16))
 (not (visible waypoint17 waypoint17))
 (visible waypoint17 waypoint18)
 (not (visible waypoint17 waypoint19))
 (visible waypoint17 waypoint20)
 (visible waypoint17 waypoint21)
 (not (visible waypoint17 waypoint22))
 (not (visible waypoint17 waypoint23))
 (not (visible waypoint17 waypoint24))
 (visible waypoint18 waypoint0)
 (visible waypoint18 waypoint1)
 (not (visible waypoint18 waypoint2))
 (visible waypoint18 waypoint3)
 (not (visible waypoint18 waypoint4))
 (not (visible waypoint18 waypoint5))
 (visible waypoint18 waypoint6)
 (not (visible waypoint18 waypoint7))
 (visible waypoint18 waypoint8)
 (visible waypoint18 waypoint9)
 (visible waypoint18 waypoint10)
 (not (visible waypoint18 waypoint11))
 (not (visible waypoint18 waypoint12))
 (not (visible waypoint18 waypoint13))
 (not (visible waypoint18 waypoint14))
 (not (visible waypoint18 waypoint15))
 (not (visible waypoint18 waypoint16))
 (visible waypoint18 waypoint17)
 (not (visible waypoint18 waypoint18))
 (not (visible waypoint18 waypoint19))
 (not (visible waypoint18 waypoint20))
 (visible waypoint18 waypoint21)
 (not (visible waypoint18 waypoint22))
 (visible waypoint18 waypoint23)
 (visible waypoint18 waypoint24)
 (not (visible waypoint19 waypoint0))
 (not (visible waypoint19 waypoint1))
 (not (visible waypoint19 waypoint2))
 (not (visible waypoint19 waypoint3))
 (visible waypoint19 waypoint4)
 (not (visible waypoint19 waypoint5))
 (visible waypoint19 waypoint6)
 (not (visible waypoint19 waypoint7))
 (not (visible waypoint19 waypoint8))
 (not (visible waypoint19 waypoint9))
 (not (visible waypoint19 waypoint10))
 (visible waypoint19 waypoint11)
 (visible waypoint19 waypoint12)
 (not (visible waypoint19 waypoint13))
 (not (visible waypoint19 waypoint14))
 (not (visible waypoint19 waypoint15))
 (not (visible waypoint19 waypoint16))
 (not (visible waypoint19 waypoint17))
 (not (visible waypoint19 waypoint18))
 (not (visible waypoint19 waypoint19))
 (visible waypoint19 waypoint20)
 (visible waypoint19 waypoint21)
 (not (visible waypoint19 waypoint22))
 (not (visible waypoint19 waypoint23))
 (not (visible waypoint19 waypoint24))
 (not (visible waypoint20 waypoint0))
 (not (visible waypoint20 waypoint1))
 (not (visible waypoint20 waypoint2))
 (visible waypoint20 waypoint3)
 (visible waypoint20 waypoint4)
 (not (visible waypoint20 waypoint5))
 (not (visible waypoint20 waypoint6))
 (not (visible waypoint20 waypoint7))
 (not (visible waypoint20 waypoint8))
 (not (visible waypoint20 waypoint9))
 (not (visible waypoint20 waypoint10))
 (not (visible waypoint20 waypoint11))
 (not (visible waypoint20 waypoint12))
 (visible waypoint20 waypoint13)
 (visible waypoint20 waypoint14)
 (not (visible waypoint20 waypoint15))
 (visible waypoint20 waypoint16)
 (visible waypoint20 waypoint17)
 (not (visible waypoint20 waypoint18))
 (visible waypoint20 waypoint19)
 (not (visible waypoint20 waypoint20))
 (not (visible waypoint20 waypoint21))
 (not (visible waypoint20 waypoint22))
 (visible waypoint20 waypoint23)
 (visible waypoint20 waypoint24)
 (not (visible waypoint21 waypoint0))
 (not (visible waypoint21 waypoint1))
 (not (visible waypoint21 waypoint2))
 (not (visible waypoint21 waypoint3))
 (visible waypoint21 waypoint4)
 (visible waypoint21 waypoint5)
 (visible waypoint21 waypoint6)
 (not (visible waypoint21 waypoint7))
 (visible waypoint21 waypoint8)
 (not (visible waypoint21 waypoint9))
 (not (visible waypoint21 waypoint10))
 (visible waypoint21 waypoint11)
 (not (visible waypoint21 waypoint12))
 (visible waypoint21 waypoint13)
 (not (visible waypoint21 waypoint14))
 (not (visible waypoint21 waypoint15))
 (not (visible waypoint21 waypoint16))
 (visible waypoint21 waypoint17)
 (visible waypoint21 waypoint18)
 (visible waypoint21 waypoint19)
 (not (visible waypoint21 waypoint20))
 (not (visible waypoint21 waypoint21))
 (visible waypoint21 waypoint22)
 (not (visible waypoint21 waypoint23))
 (not (visible waypoint21 waypoint24))
 (not (visible waypoint22 waypoint0))
 (not (visible waypoint22 waypoint1))
 (not (visible waypoint22 waypoint2))
 (not (visible waypoint22 waypoint3))
 (not (visible waypoint22 waypoint4))
 (not (visible waypoint22 waypoint5))
 (not (visible waypoint22 waypoint6))
 (not (visible waypoint22 waypoint7))
 (not (visible waypoint22 waypoint8))
 (not (visible waypoint22 waypoint9))
 (not (visible waypoint22 waypoint10))
 (visible waypoint22 waypoint11)
 (visible waypoint22 waypoint12)
 (not (visible waypoint22 waypoint13))
 (not (visible waypoint22 waypoint14))
 (not (visible waypoint22 waypoint15))
 (visible waypoint22 waypoint16)
 (not (visible waypoint22 waypoint17))
 (not (visible waypoint22 waypoint18))
 (not (visible waypoint22 waypoint19))
 (not (visible waypoint22 waypoint20))
 (visible waypoint22 waypoint21)
 (not (visible waypoint22 waypoint22))
 (not (visible waypoint22 waypoint23))
 (not (visible waypoint22 waypoint24))
 (visible waypoint23 waypoint0)
 (visible waypoint23 waypoint1)
 (visible waypoint23 waypoint2)
 (not (visible waypoint23 waypoint3))
 (not (visible waypoint23 waypoint4))
 (not (visible waypoint23 waypoint5))
 (not (visible waypoint23 waypoint6))
 (not (visible waypoint23 waypoint7))
 (not (visible waypoint23 waypoint8))
 (not (visible waypoint23 waypoint9))
 (visible waypoint23 waypoint10)
 (not (visible waypoint23 waypoint11))
 (visible waypoint23 waypoint12)
 (not (visible waypoint23 waypoint13))
 (not (visible waypoint23 waypoint14))
 (not (visible waypoint23 waypoint15))
 (not (visible waypoint23 waypoint16))
 (not (visible waypoint23 waypoint17))
 (visible waypoint23 waypoint18)
 (not (visible waypoint23 waypoint19))
 (visible waypoint23 waypoint20)
 (not (visible waypoint23 waypoint21))
 (not (visible waypoint23 waypoint22))
 (not (visible waypoint23 waypoint23))
 (visible waypoint23 waypoint24)
 (not (visible waypoint24 waypoint0))
 (not (visible waypoint24 waypoint1))
 (not (visible waypoint24 waypoint2))
 (not (visible waypoint24 waypoint3))
 (not (visible waypoint24 waypoint4))
 (visible waypoint24 waypoint5)
 (not (visible waypoint24 waypoint6))
 (visible waypoint24 waypoint7)
 (not (visible waypoint24 waypoint8))
 (not (visible waypoint24 waypoint9))
 (not (visible waypoint24 waypoint10))
 (not (visible waypoint24 waypoint11))
 (visible waypoint24 waypoint12)
 (not (visible waypoint24 waypoint13))
 (not (visible waypoint24 waypoint14))
 (not (visible waypoint24 waypoint15))
 (not (visible waypoint24 waypoint16))
 (not (visible waypoint24 waypoint17))
 (visible waypoint24 waypoint18)
 (not (visible waypoint24 waypoint19))
 (visible waypoint24 waypoint20)
 (not (visible waypoint24 waypoint21))
 (not (visible waypoint24 waypoint22))
 (visible waypoint24 waypoint23)
 (not (visible waypoint24 waypoint24))
 (not (communicated_soil_data waypoint0))
 (not (communicated_soil_data waypoint1))
 (not (communicated_soil_data waypoint2))
 (not (communicated_soil_data waypoint3))
 (not (communicated_soil_data waypoint4))
 (not (communicated_soil_data waypoint5))
 (not (communicated_soil_data waypoint6))
 (not (communicated_soil_data waypoint7))
 (not (communicated_soil_data waypoint8))
 (not (communicated_soil_data waypoint9))
 (not (communicated_soil_data waypoint10))
 (not (communicated_soil_data waypoint11))
 (not (communicated_soil_data waypoint12))
 (not (communicated_soil_data waypoint13))
 (not (communicated_soil_data waypoint14))
 (not (communicated_soil_data waypoint15))
 (not (communicated_soil_data waypoint16))
 (not (communicated_soil_data waypoint17))
 (not (communicated_soil_data waypoint18))
 (not (communicated_soil_data waypoint19))
 (not (communicated_soil_data waypoint20))
 (not (communicated_soil_data waypoint21))
 (not (communicated_soil_data waypoint22))
 (not (communicated_soil_data waypoint23))
 (not (communicated_soil_data waypoint24))
 (not (communicated_rock_data waypoint0))
 (not (communicated_rock_data waypoint1))
 (not (communicated_rock_data waypoint2))
 (not (communicated_rock_data waypoint3))
 (not (communicated_rock_data waypoint4))
 (not (communicated_rock_data waypoint5))
 (not (communicated_rock_data waypoint6))
 (not (communicated_rock_data waypoint7))
 (not (communicated_rock_data waypoint8))
 (not (communicated_rock_data waypoint9))
 (not (communicated_rock_data waypoint10))
 (not (communicated_rock_data waypoint11))
 (not (communicated_rock_data waypoint12))
 (not (communicated_rock_data waypoint13))
 (not (communicated_rock_data waypoint14))
 (not (communicated_rock_data waypoint15))
 (not (communicated_rock_data waypoint16))
 (not (communicated_rock_data waypoint17))
 (not (communicated_rock_data waypoint18))
 (not (communicated_rock_data waypoint19))
 (not (communicated_rock_data waypoint20))
 (not (communicated_rock_data waypoint21))
 (not (communicated_rock_data waypoint22))
 (not (communicated_rock_data waypoint23))
 (not (communicated_rock_data waypoint24))
 (at_soil_sample waypoint0)
 (at_soil_sample waypoint1)
 (not (at_soil_sample waypoint2))
 (not (at_soil_sample waypoint3))
 (not (at_soil_sample waypoint4))
 (not (at_soil_sample waypoint5))
 (not (at_soil_sample waypoint6))
 (at_soil_sample waypoint7)
 (at_soil_sample waypoint8)
 (at_soil_sample waypoint9)
 (not (at_soil_sample waypoint10))
 (at_soil_sample waypoint11)
 (not (at_soil_sample waypoint12))
 (at_soil_sample waypoint13)
 (not (at_soil_sample waypoint14))
 (at_soil_sample waypoint15)
 (not (at_soil_sample waypoint16))
 (at_soil_sample waypoint17)
 (at_soil_sample waypoint18)
 (not (at_soil_sample waypoint19))
 (at_soil_sample waypoint20)
 (not (at_soil_sample waypoint21))
 (at_soil_sample waypoint22)
 (at_soil_sample waypoint23)
 (at_soil_sample waypoint24)
 (not (at_rock_sample waypoint0))
 (not (at_rock_sample waypoint1))
 (not (at_rock_sample waypoint2))
 (not (at_rock_sample waypoint3))
 (not (at_rock_sample waypoint4))
 (not (at_rock_sample waypoint5))
 (not (at_rock_sample waypoint6))
 (at_rock_sample waypoint7)
 (not (at_rock_sample waypoint8))
 (at_rock_sample waypoint9)
 (at_rock_sample waypoint10)
 (not (at_rock_sample waypoint11))
 (at_rock_sample waypoint12)
 (not (at_rock_sample waypoint13))
 (at_rock_sample waypoint14)
 (not (at_rock_sample waypoint15))
 (at_rock_sample waypoint16)
 (not (at_rock_sample waypoint17))
 (at_rock_sample waypoint18)
 (not (at_rock_sample waypoint19))
 (not (at_rock_sample waypoint20))
 (at_rock_sample waypoint21)
 (at_rock_sample waypoint22)
 (not (at_rock_sample waypoint23))
 (not (at_rock_sample waypoint24))
 (not (calibrated camera0 rover2))
 (not (calibrated camera1 rover2))
 (not (calibrated camera2 rover2))
 (not (calibrated camera3 rover2))
 (not (calibrated camera4 rover2))
 (not (calibrated camera5 rover2))
 (not (calibrated camera6 rover2))
 (supports camera0 colour)
 (supports camera0 high_res)
 (not (supports camera0 low_res))
 (supports camera1 colour)
 (supports camera1 high_res)
 (not (supports camera1 low_res))
 (supports camera2 colour)
 (supports camera2 high_res)
 (supports camera2 low_res)
 (not (supports camera3 colour))
 (supports camera3 high_res)
 (supports camera3 low_res)
 (supports camera4 colour)
 (supports camera4 high_res)
 (not (supports camera4 low_res))
 (not (supports camera5 colour))
 (supports camera5 high_res)
 (not (supports camera5 low_res))
 (supports camera6 colour)
 (supports camera6 high_res)
 (supports camera6 low_res)
 (not (have_image rover2 objective0 colour))
 (not (have_image rover2 objective0 high_res))
 (not (have_image rover2 objective0 low_res))
 (not (have_image rover2 objective1 colour))
 (not (have_image rover2 objective1 high_res))
 (not (have_image rover2 objective1 low_res))
 (not (have_image rover2 objective2 colour))
 (not (have_image rover2 objective2 high_res))
 (not (have_image rover2 objective2 low_res))
 (not (have_image rover2 objective3 colour))
 (not (have_image rover2 objective3 high_res))
 (not (have_image rover2 objective3 low_res))
 (not (have_image rover2 objective4 colour))
 (not (have_image rover2 objective4 high_res))
 (not (have_image rover2 objective4 low_res))
 (not (have_image rover2 objective5 colour))
 (not (have_image rover2 objective5 high_res))
 (not (have_image rover2 objective5 low_res))
 (not (have_image rover2 objective6 colour))
 (not (have_image rover2 objective6 high_res))
 (not (have_image rover2 objective6 low_res))
 (not (have_image rover2 objective7 colour))
 (not (have_image rover2 objective7 high_res))
 (not (have_image rover2 objective7 low_res))
 (not (communicated_image_data objective0 colour))
 (not (communicated_image_data objective0 high_res))
 (not (communicated_image_data objective0 low_res))
 (not (communicated_image_data objective1 colour))
 (not (communicated_image_data objective1 high_res))
 (not (communicated_image_data objective1 low_res))
 (not (communicated_image_data objective2 colour))
 (not (communicated_image_data objective2 high_res))
 (not (communicated_image_data objective2 low_res))
 (not (communicated_image_data objective3 colour))
 (not (communicated_image_data objective3 high_res))
 (not (communicated_image_data objective3 low_res))
 (not (communicated_image_data objective4 colour))
 (not (communicated_image_data objective4 high_res))
 (not (communicated_image_data objective4 low_res))
 (not (communicated_image_data objective5 colour))
 (not (communicated_image_data objective5 high_res))
 (not (communicated_image_data objective5 low_res))
 (not (communicated_image_data objective6 colour))
 (not (communicated_image_data objective6 high_res))
 (not (communicated_image_data objective6 low_res))
 (not (communicated_image_data objective7 colour))
 (not (communicated_image_data objective7 high_res))
 (not (communicated_image_data objective7 low_res))
 (visible_from objective0 waypoint0)
 (visible_from objective0 waypoint1)
 (visible_from objective0 waypoint2)
 (visible_from objective0 waypoint3)
 (visible_from objective0 waypoint4)
 (visible_from objective0 waypoint5)
 (visible_from objective0 waypoint6)
 (visible_from objective0 waypoint7)
 (visible_from objective0 waypoint8)
 (visible_from objective0 waypoint9)
 (visible_from objective0 waypoint10)
 (visible_from objective0 waypoint11)
 (visible_from objective0 waypoint12)
 (visible_from objective0 waypoint13)
 (visible_from objective0 waypoint14)
 (visible_from objective0 waypoint15)
 (visible_from objective0 waypoint16)
 (not (visible_from objective0 waypoint17))
 (not (visible_from objective0 waypoint18))
 (not (visible_from objective0 waypoint19))
 (not (visible_from objective0 waypoint20))
 (not (visible_from objective0 waypoint21))
 (not (visible_from objective0 waypoint22))
 (not (visible_from objective0 waypoint23))
 (not (visible_from objective0 waypoint24))
 (visible_from objective1 waypoint0)
 (visible_from objective1 waypoint1)
 (visible_from objective1 waypoint2)
 (visible_from objective1 waypoint3)
 (not (visible_from objective1 waypoint4))
 (not (visible_from objective1 waypoint5))
 (not (visible_from objective1 waypoint6))
 (not (visible_from objective1 waypoint7))
 (not (visible_from objective1 waypoint8))
 (not (visible_from objective1 waypoint9))
 (not (visible_from objective1 waypoint10))
 (not (visible_from objective1 waypoint11))
 (not (visible_from objective1 waypoint12))
 (not (visible_from objective1 waypoint13))
 (not (visible_from objective1 waypoint14))
 (not (visible_from objective1 waypoint15))
 (not (visible_from objective1 waypoint16))
 (not (visible_from objective1 waypoint17))
 (not (visible_from objective1 waypoint18))
 (not (visible_from objective1 waypoint19))
 (not (visible_from objective1 waypoint20))
 (not (visible_from objective1 waypoint21))
 (not (visible_from objective1 waypoint22))
 (not (visible_from objective1 waypoint23))
 (not (visible_from objective1 waypoint24))
 (visible_from objective2 waypoint0)
 (visible_from objective2 waypoint1)
 (visible_from objective2 waypoint2)
 (visible_from objective2 waypoint3)
 (visible_from objective2 waypoint4)
 (visible_from objective2 waypoint5)
 (visible_from objective2 waypoint6)
 (visible_from objective2 waypoint7)
 (visible_from objective2 waypoint8)
 (visible_from objective2 waypoint9)
 (visible_from objective2 waypoint10)
 (visible_from objective2 waypoint11)
 (visible_from objective2 waypoint12)
 (visible_from objective2 waypoint13)
 (visible_from objective2 waypoint14)
 (visible_from objective2 waypoint15)
 (visible_from objective2 waypoint16)
 (visible_from objective2 waypoint17)
 (not (visible_from objective2 waypoint18))
 (not (visible_from objective2 waypoint19))
 (not (visible_from objective2 waypoint20))
 (not (visible_from objective2 waypoint21))
 (not (visible_from objective2 waypoint22))
 (not (visible_from objective2 waypoint23))
 (not (visible_from objective2 waypoint24))
 (visible_from objective3 waypoint0)
 (visible_from objective3 waypoint1)
 (visible_from objective3 waypoint2)
 (visible_from objective3 waypoint3)
 (visible_from objective3 waypoint4)
 (visible_from objective3 waypoint5)
 (visible_from objective3 waypoint6)
 (visible_from objective3 waypoint7)
 (visible_from objective3 waypoint8)
 (visible_from objective3 waypoint9)
 (visible_from objective3 waypoint10)
 (visible_from objective3 waypoint11)
 (visible_from objective3 waypoint12)
 (visible_from objective3 waypoint13)
 (visible_from objective3 waypoint14)
 (visible_from objective3 waypoint15)
 (visible_from objective3 waypoint16)
 (visible_from objective3 waypoint17)
 (visible_from objective3 waypoint18)
 (visible_from objective3 waypoint19)
 (not (visible_from objective3 waypoint20))
 (not (visible_from objective3 waypoint21))
 (not (visible_from objective3 waypoint22))
 (not (visible_from objective3 waypoint23))
 (not (visible_from objective3 waypoint24))
 (visible_from objective4 waypoint0)
 (visible_from objective4 waypoint1)
 (visible_from objective4 waypoint2)
 (visible_from objective4 waypoint3)
 (visible_from objective4 waypoint4)
 (visible_from objective4 waypoint5)
 (visible_from objective4 waypoint6)
 (visible_from objective4 waypoint7)
 (visible_from objective4 waypoint8)
 (visible_from objective4 waypoint9)
 (visible_from objective4 waypoint10)
 (visible_from objective4 waypoint11)
 (visible_from objective4 waypoint12)
 (visible_from objective4 waypoint13)
 (visible_from objective4 waypoint14)
 (visible_from objective4 waypoint15)
 (visible_from objective4 waypoint16)
 (visible_from objective4 waypoint17)
 (visible_from objective4 waypoint18)
 (visible_from objective4 waypoint19)
 (visible_from objective4 waypoint20)
 (visible_from objective4 waypoint21)
 (visible_from objective4 waypoint22)
 (visible_from objective4 waypoint23)
 (not (visible_from objective4 waypoint24))
 (visible_from objective5 waypoint0)
 (visible_from objective5 waypoint1)
 (visible_from objective5 waypoint2)
 (visible_from objective5 waypoint3)
 (visible_from objective5 waypoint4)
 (visible_from objective5 waypoint5)
 (visible_from objective5 waypoint6)
 (visible_from objective5 waypoint7)
 (visible_from objective5 waypoint8)
 (visible_from objective5 waypoint9)
 (visible_from objective5 waypoint10)
 (visible_from objective5 waypoint11)
 (visible_from objective5 waypoint12)
 (visible_from objective5 waypoint13)
 (visible_from objective5 waypoint14)
 (not (visible_from objective5 waypoint15))
 (not (visible_from objective5 waypoint16))
 (not (visible_from objective5 waypoint17))
 (not (visible_from objective5 waypoint18))
 (not (visible_from objective5 waypoint19))
 (not (visible_from objective5 waypoint20))
 (not (visible_from objective5 waypoint21))
 (not (visible_from objective5 waypoint22))
 (not (visible_from objective5 waypoint23))
 (not (visible_from objective5 waypoint24))
 (visible_from objective6 waypoint0)
 (visible_from objective6 waypoint1)
 (visible_from objective6 waypoint2)
 (visible_from objective6 waypoint3)
 (visible_from objective6 waypoint4)
 (visible_from objective6 waypoint5)
 (visible_from objective6 waypoint6)
 (visible_from objective6 waypoint7)
 (visible_from objective6 waypoint8)
 (visible_from objective6 waypoint9)
 (visible_from objective6 waypoint10)
 (not (visible_from objective6 waypoint11))
 (not (visible_from objective6 waypoint12))
 (not (visible_from objective6 waypoint13))
 (not (visible_from objective6 waypoint14))
 (not (visible_from objective6 waypoint15))
 (not (visible_from objective6 waypoint16))
 (not (visible_from objective6 waypoint17))
 (not (visible_from objective6 waypoint18))
 (not (visible_from objective6 waypoint19))
 (not (visible_from objective6 waypoint20))
 (not (visible_from objective6 waypoint21))
 (not (visible_from objective6 waypoint22))
 (not (visible_from objective6 waypoint23))
 (not (visible_from objective6 waypoint24))
 (visible_from objective7 waypoint0)
 (visible_from objective7 waypoint1)
 (visible_from objective7 waypoint2)
 (visible_from objective7 waypoint3)
 (visible_from objective7 waypoint4)
 (visible_from objective7 waypoint5)
 (visible_from objective7 waypoint6)
 (visible_from objective7 waypoint7)
 (visible_from objective7 waypoint8)
 (visible_from objective7 waypoint9)
 (visible_from objective7 waypoint10)
 (visible_from objective7 waypoint11)
 (visible_from objective7 waypoint12)
 (visible_from objective7 waypoint13)
 (visible_from objective7 waypoint14)
 (visible_from objective7 waypoint15)
 (visible_from objective7 waypoint16)
 (visible_from objective7 waypoint17)
 (visible_from objective7 waypoint18)
 (visible_from objective7 waypoint19)
 (visible_from objective7 waypoint20)
 (not (visible_from objective7 waypoint21))
 (not (visible_from objective7 waypoint22))
 (not (visible_from objective7 waypoint23))
 (not (visible_from objective7 waypoint24))
 (= (at rover2) waypoint3)
 (= (at_lander general) waypoint1)
 (= (store_of rover0store) rover0)
 (= (store_of rover1store) rover1)
 (= (store_of rover2store) rover2)
 (= (store_of rover3store) rover3)
 (= (store_of rover4store) rover4)
 (= (store_of rover5store) rover5)
 (= (store_of rover6store) rover6)
 (= (store_of rover7store) rover7)
 (= (calibration_target camera0) objective6)
 (= (calibration_target camera1) objective1)
 (= (calibration_target camera2) objective0)
 (= (calibration_target camera3) objective2)
 (= (calibration_target camera4) objective4)
 (= (calibration_target camera5) objective4)
 (= (calibration_target camera6) objective5)
 (= (on_board camera0) rover0)
 (= (on_board camera1) rover1)
 (= (on_board camera2) rover4)
 (= (on_board camera3) rover2)
 (= (on_board camera4) rover1)
 (= (on_board camera5) rover5)
 (= (on_board camera6) rover6)
)
(:global-goal (and
 (communicated_soil_data waypoint8)
 (communicated_soil_data waypoint23)
 (communicated_soil_data waypoint7)
 (communicated_soil_data waypoint11)
 (communicated_soil_data waypoint13)
 (communicated_soil_data waypoint20)
 (communicated_rock_data waypoint7)
 (communicated_rock_data waypoint14)
 (communicated_rock_data waypoint22)
 (communicated_rock_data waypoint16)
 (communicated_rock_data waypoint12)
 (communicated_rock_data waypoint10)
 (communicated_rock_data waypoint9)
 (communicated_rock_data waypoint21)
 (communicated_rock_data waypoint18)
 (communicated_image_data objective2 high_res)
 (communicated_image_data objective0 high_res)
 (communicated_image_data objective3 colour)
 (communicated_image_data objective7 colour)
 (communicated_image_data objective5 high_res)
))
)
