(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
 satellite0 satellite1 satellite2 satellite3 satellite4 satellite5 satellite6 satellite7 satellite8 satellite9 - satellite
 instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11 instrument12 instrument13 instrument14 instrument15 instrument16 instrument17 instrument18 instrument19 instrument20 instrument21 instrument22 - instrument
 image0 image2 infrared4 thermograph1 spectrograph3 - mode
 groundstation0 star3 groundstation4 star2 groundstation1 phenomenon5 planet6 planet7 planet8 phenomenon9 planet10 planet11 star12 star13 star14 star15 star16 phenomenon17 phenomenon18 planet19 star20 planet21 planet22 phenomenon23 star24 - direction
)
(:shared-data
  ((pointing ?s - satellite) - direction)
  (have_image ?d - direction ?m - mode) - (either satellite0 satellite1 satellite2 satellite3 satellite5 satellite6 satellite7 satellite8 satellite9)
)
(:init (mySatellite satellite4)
 (power_avail satellite4)
 (not (power_on instrument0))
 (not (calibrated instrument0))
 (= (calibration_target instrument0) star3)
 (not (power_on instrument1))
 (not (calibrated instrument1))
 (= (calibration_target instrument1) groundstation0)
 (not (power_on instrument2))
 (not (calibrated instrument2))
 (= (calibration_target instrument2) groundstation1)
 (not (power_on instrument3))
 (not (calibrated instrument3))
 (= (calibration_target instrument3) groundstation4)
 (not (power_on instrument4))
 (not (calibrated instrument4))
 (= (calibration_target instrument4) star3)
 (not (power_on instrument5))
 (not (calibrated instrument5))
 (= (calibration_target instrument5) groundstation4)
 (not (power_on instrument6))
 (not (calibrated instrument6))
 (= (calibration_target instrument6) groundstation1)
 (not (power_on instrument7))
 (not (calibrated instrument7))
 (= (calibration_target instrument7) star3)
 (not (power_on instrument8))
 (not (calibrated instrument8))
 (= (calibration_target instrument8) groundstation0)
 (not (power_on instrument9))
 (not (calibrated instrument9))
 (= (calibration_target instrument9) star3)
 (not (power_on instrument10))
 (not (calibrated instrument10))
 (= (calibration_target instrument10) star2)
 (not (power_on instrument11))
 (not (calibrated instrument11))
 (= (calibration_target instrument11) star3)
 (not (power_on instrument12))
 (not (calibrated instrument12))
 (= (calibration_target instrument12) groundstation4)
 (not (power_on instrument13))
 (not (calibrated instrument13))
 (= (calibration_target instrument13) star2)
 (not (power_on instrument14))
 (not (calibrated instrument14))
 (= (calibration_target instrument14) star3)
 (not (power_on instrument15))
 (not (calibrated instrument15))
 (= (calibration_target instrument15) groundstation4)
 (not (power_on instrument16))
 (not (calibrated instrument16))
 (= (calibration_target instrument16) groundstation0)
 (not (power_on instrument17))
 (not (calibrated instrument17))
 (= (calibration_target instrument17) groundstation4)
 (not (power_on instrument18))
 (not (calibrated instrument18))
 (= (calibration_target instrument18) star3)
 (not (power_on instrument19))
 (not (calibrated instrument19))
 (= (calibration_target instrument19) star2)
 (not (power_on instrument20))
 (not (calibrated instrument20))
 (= (calibration_target instrument20) groundstation4)
 (not (power_on instrument21))
 (not (calibrated instrument21))
 (= (calibration_target instrument21) star2)
 (not (power_on instrument22))
 (not (calibrated instrument22))
 (= (calibration_target instrument22) groundstation1)
 (not (have_image phenomenon5 thermograph1))
 (not (have_image planet6 infrared4))
 (not (have_image planet7 image0))
 (not (have_image planet8 thermograph1))
 (not (have_image phenomenon9 image2))
 (not (have_image planet10 image0))
 (not (have_image planet11 infrared4))
 (not (have_image star12 image0))
 (not (have_image star13 image0))
 (not (have_image star14 thermograph1))
 (not (have_image star15 image0))
 (not (have_image star16 thermograph1))
 (not (have_image phenomenon17 infrared4))
 (not (have_image phenomenon18 spectrograph3))
 (not (have_image star20 image0))
 (not (have_image planet21 thermograph1))
 (not (have_image planet22 image2))
 (not (have_image phenomenon23 image0))
 (not (have_image star24 infrared4))
 (= (pointing satellite4) planet19)
 (= (on_board satellite4) {instrument8 instrument9 instrument10})
 (not (= (on_board satellite4) {instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument11 instrument12 instrument13 instrument14 instrument15 instrument16 instrument17 instrument18 instrument19 instrument20 instrument21 instrument22}))
 (= (supports instrument0) {infrared4})
 (not (= (supports instrument0) {image0 image2 thermograph1 spectrograph3}))
 (= (supports instrument1) {spectrograph3})
 (not (= (supports instrument1) {image0 image2 infrared4 thermograph1}))
 (= (supports instrument2) {image0 image2 thermograph1})
 (not (= (supports instrument2) {infrared4 spectrograph3}))
 (= (supports instrument3) {image0 thermograph1})
 (not (= (supports instrument3) {image2 infrared4 spectrograph3}))
 (= (supports instrument4) {image2 thermograph1})
 (not (= (supports instrument4) {image0 infrared4 spectrograph3}))
 (= (supports instrument5) {image2 thermograph1 spectrograph3})
 (not (= (supports instrument5) {image0 infrared4}))
 (= (supports instrument6) {image0})
 (not (= (supports instrument6) {image2 infrared4 thermograph1 spectrograph3}))
 (= (supports instrument7) {infrared4})
 (not (= (supports instrument7) {image0 image2 thermograph1 spectrograph3}))
 (= (supports instrument8) {spectrograph3})
 (not (= (supports instrument8) {image0 image2 infrared4 thermograph1}))
 (= (supports instrument9) {image0 image2 thermograph1})
 (not (= (supports instrument9) {infrared4 spectrograph3}))
 (= (supports instrument10) {image0 image2 spectrograph3})
 (not (= (supports instrument10) {infrared4 thermograph1}))
 (= (supports instrument11) {image0})
 (not (= (supports instrument11) {image2 infrared4 thermograph1 spectrograph3}))
 (= (supports instrument12) {image0 infrared4})
 (not (= (supports instrument12) {image2 thermograph1 spectrograph3}))
 (= (supports instrument13) {spectrograph3})
 (not (= (supports instrument13) {image0 image2 infrared4 thermograph1}))
 (= (supports instrument14) {image0 thermograph1 spectrograph3})
 (not (= (supports instrument14) {image2 infrared4}))
 (= (supports instrument15) {image0 image2 thermograph1})
 (not (= (supports instrument15) {infrared4 spectrograph3}))
 (= (supports instrument16) {image2 spectrograph3})
 (not (= (supports instrument16) {image0 infrared4 thermograph1}))
 (= (supports instrument17) {image0 image2 thermograph1})
 (not (= (supports instrument17) {infrared4 spectrograph3}))
 (= (supports instrument18) {image2 thermograph1})
 (not (= (supports instrument18) {image0 infrared4 spectrograph3}))
 (= (supports instrument19) {infrared4 thermograph1})
 (not (= (supports instrument19) {image0 image2 spectrograph3}))
 (= (supports instrument20) {thermograph1})
 (not (= (supports instrument20) {image0 image2 infrared4 spectrograph3}))
 (= (supports instrument21) {thermograph1})
 (not (= (supports instrument21) {image0 image2 infrared4 spectrograph3}))
 (= (supports instrument22) {infrared4 thermograph1 spectrograph3})
 (not (= (supports instrument22) {image0 image2}))
)
(:global-goal (and
 (= (pointing satellite5) planet6)
 (= (pointing satellite7) star3)
 (= (pointing satellite8) star15)
 (= (pointing satellite9) star16)
 (have_image phenomenon5 thermograph1)
 (have_image planet6 infrared4)
 (have_image planet7 image0)
 (have_image planet8 thermograph1)
 (have_image phenomenon9 image2)
 (have_image planet10 image0)
 (have_image planet11 infrared4)
 (have_image star12 image0)
 (have_image star13 image0)
 (have_image star14 thermograph1)
 (have_image star15 image0)
 (have_image star16 thermograph1)
 (have_image phenomenon17 infrared4)
 (have_image phenomenon18 spectrograph3)
 (have_image star20 image0)
 (have_image planet21 thermograph1)
 (have_image planet22 image2)
 (have_image phenomenon23 image0)
 (have_image star24 infrared4)
))
)
