(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
 satellite0 satellite1 satellite2 - satellite
 instrument0 instrument1 instrument2 instrument3 instrument4 - instrument
 thermograph2 spectrograph0 infrared1 infrared3 - mode
 groundstation3 star1 star2 star0 planet4 planet5 star6 star7 phenomenon8 star9 star10 - direction
)
(:shared-data
  ((pointing ?s - satellite) - direction)
  (have_image ?d - direction ?m - mode) - (either satellite0 satellite2)
)
(:init (mySatellite satellite1)
 (power_avail satellite1)
 (not (power_on instrument0))
 (not (calibrated instrument0))
 (= (calibration_target instrument0) star1)
 (not (power_on instrument1))
 (not (calibrated instrument1))
 (= (calibration_target instrument1) star2)
 (not (power_on instrument2))
 (not (calibrated instrument2))
 (= (calibration_target instrument2) star2)
 (not (power_on instrument3))
 (not (calibrated instrument3))
 (= (calibration_target instrument3) star2)
 (not (power_on instrument4))
 (not (calibrated instrument4))
 (= (calibration_target instrument4) star0)
 (not (have_image planet4 thermograph2))
 (not (have_image planet5 spectrograph0))
 (not (have_image star6 thermograph2))
 (not (have_image star7 infrared3))
 (not (have_image phenomenon8 spectrograph0))
 (not (have_image star9 infrared1))
 (not (have_image star10 infrared3))
 (= (pointing satellite1) star6)
 (= (on_board satellite1) {instrument1 instrument2 instrument3})
 (not (= (on_board satellite1) {instrument0 instrument4}))
 (= (supports instrument0) {spectrograph0 infrared1})
 (not (= (supports instrument0) {thermograph2 infrared3}))
 (= (supports instrument1) {infrared3})
 (not (= (supports instrument1) {thermograph2 spectrograph0 infrared1}))
 (= (supports instrument2) {thermograph2 infrared1 infrared3})
 (not (= (supports instrument2) {spectrograph0}))
 (= (supports instrument3) {spectrograph0 infrared1 infrared3})
 (not (= (supports instrument3) {thermograph2}))
 (= (supports instrument4) {infrared3})
 (not (= (supports instrument4) {thermograph2 spectrograph0 infrared1}))
)
(:global-goal (and
 (have_image planet4 thermograph2)
 (have_image planet5 spectrograph0)
 (have_image star6 thermograph2)
 (have_image star7 infrared3)
 (have_image phenomenon8 spectrograph0)
 (have_image star9 infrared1)
 (have_image star10 infrared3)
))
)
