(define (problem depotprob7512) (:domain Depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 - pallet
	crate0 crate1 crate2 crate3 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate0)
	(at pallet1 distributor0)
	(clear crate3)
	(at pallet2 distributor1)
	(clear crate2)
	(at truck0 depot0)
	(= (speed truck0) 3)
	(at truck1 depot0)
	(= (speed truck1) 1)
	(at hoist0 depot0)
	(available hoist0)
	(= (power hoist0) 9)
	(at hoist1 distributor0)
	(available hoist1)
	(= (power hoist1) 4)
	(at hoist2 distributor1)
	(available hoist2)
	(= (power hoist2) 3)
	(at crate0 depot0)
	(on crate0 pallet0)
	(= (weight crate0) 32)
	(at crate1 distributor1)
	(on crate1 pallet2)
	(= (weight crate1) 4)
	(at crate2 distributor1)
	(on crate2 crate1)
	(= (weight crate2) 89)
	(at crate3 distributor0)
	(on crate3 pallet1)
	(= (weight crate3) 62)
	(= (distance depot0 depot0) 0)
	(= (distance depot0 distributor0) 1)
	(= (distance depot0 distributor1) 10)
	(= (distance distributor0 depot0) 2)
	(= (distance distributor0 distributor0) 0)
	(= (distance distributor0 distributor1) 9)
	(= (distance distributor1 depot0) 10)
	(= (distance distributor1 distributor0) 2)
	(= (distance distributor1 distributor1) 0)
)

(:goal (and
		(on crate0 pallet2)
		(on crate1 crate3)
		(on crate2 pallet0)
		(on crate3 pallet1)
	)
)

;(:metric minimize (total-time))
)
