(define (problem BLOCKS-10-1)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 b g e d f h i a c j - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r0 r2 r3)
)
(:init
 (myAgent r1)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear b))
 (ontable b)
 (= (on b) nob)
 (not (clear g))
 (= (on g) e)
 (not (ontable g))
 (not (clear e))
 (= (on e) i)
 (not (ontable e))
 (not (clear d))
 (= (on d) h)
 (not (ontable d))
 (clear f)
 (= (on f) d)
 (not (ontable f))
 (not (clear h))
 (ontable h)
 (= (on h) nob)
 (not (clear i))
 (= (on i) j)
 (not (ontable i))
 (not (clear a))
 (= (on a) b)
 (not (ontable a))
 (clear c)
 (= (on c) g)
 (not (ontable c))
 (not (clear j))
 (= (on j) a)
 (not (ontable j))
)
(:global-goal (and
 (= (on c) b)
 (= (on b) d)
 (= (on d) f)
 (= (on f) i)
 (= (on i) a)
 (= (on a) e)
 (= (on e) h)
 (= (on h) g)
 (= (on g) j)
)))
