(define (problem BLOCKS-16-1)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 k i g n p a d m c b h f o j l e - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r0 r2 r3)
)
(:init
 (myAgent r1)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear k))
 (= (on k) a)
 (not (ontable k))
 (not (clear i))
 (= (on i) b)
 (not (ontable i))
 (not (clear g))
 (ontable g)
 (= (on g) nob)
 (not (clear n))
 (= (on n) i)
 (not (ontable n))
 (not (clear p))
 (= (on p) n)
 (not (ontable p))
 (not (clear a))
 (ontable a)
 (= (on a) nob)
 (not (clear d))
 (= (on d) c)
 (not (ontable d))
 (not (clear m))
 (= (on m) j)
 (not (ontable m))
 (not (clear c))
 (= (on c) k)
 (not (ontable c))
 (not (clear b))
 (= (on b) d)
 (not (ontable b))
 (clear h)
 (= (on h) e)
 (not (ontable h))
 (clear f)
 (= (on f) l)
 (not (ontable f))
 (clear o)
 (= (on o) g)
 (not (ontable o))
 (not (clear j))
 (= (on j) p)
 (not (ontable j))
 (not (clear l))
 (= (on l) m)
 (not (ontable l))
 (not (clear e))
 (ontable e)
 (= (on e) nob)
)
(:global-goal (and
 (= (on d) b)
 (= (on b) p)
 (= (on p) f)
 (= (on f) g)
 (= (on g) k)
 (= (on k) i)
 (= (on i) l)
 (= (on l) j)
 (= (on j) h)
 (= (on h) a)
 (= (on a) n)
 (= (on n) e)
 (= (on e) m)
 (= (on m) c)
 (= (on c) o)
)))
