(define (problem elevators-sequencedstrips-p8_3_1)
(:domain elevators)
(:objects
 n0 n1 n2 n3 n4 n5 n6 n7 n8 - count
 p0 p1 p2 - passenger
 fast0 - fast-elevator
 slow0-0 slow1-0 - slow-elevator
)
(:shared-data
  ((at ?person - passenger) - (either count elevator)) - (either slow0-0 slow1-0)
)
(:init (myAgent fast0)
 (= (next n0) n1)
 (= (next n1) n2)
 (= (next n2) n3)
 (= (next n3) n4)
 (= (next n4) n5)
 (= (next n5) n6)
 (= (next n6) n7)
 (= (next n7) n8)
 (above n0 n1)
 (above n0 n2)
 (above n0 n3)
 (above n0 n4)
 (above n0 n5)
 (above n0 n6)
 (above n0 n7)
 (above n0 n8)
 (above n1 n2)
 (above n1 n3)
 (above n1 n4)
 (above n1 n5)
 (above n1 n6)
 (above n1 n7)
 (above n1 n8)
 (above n2 n3)
 (above n2 n4)
 (above n2 n5)
 (above n2 n6)
 (above n2 n7)
 (above n2 n8)
 (above n3 n4)
 (above n3 n5)
 (above n3 n6)
 (above n3 n7)
 (above n3 n8)
 (above n4 n5)
 (above n4 n6)
 (above n4 n7)
 (above n4 n8)
 (above n5 n6)
 (above n5 n7)
 (above n5 n8)
 (above n6 n7)
 (above n6 n8)
 (above n7 n8)
 (= (lift-at fast0) n0)
 (= (passengers fast0) n0)
 (reachable-floor fast0 n0)
 (can-hold fast0 n1)
 (can-hold fast0 n2)
 (reachable-floor fast0 n2)
 (can-hold fast0 n3)
 (reachable-floor fast0 n4)
 (reachable-floor fast0 n6)
 (reachable-floor fast0 n8)
 (= (at p0) n8)
 (= (at p1) n3)
 (= (at p2) n2)
)
(:global-goal (and
 (= (at p0) n4)
 (= (at p1) n6)
 (= (at p2) n1)
))
)
