(define (problem BLOCKS-6-2)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 f d c e b a - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r1 r2 r3)
)
(:init
 (myAgent r0)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear f))
 (= (on f) e)
 (not (ontable f))
 (not (clear d))
 (= (on d) b)
 (not (ontable d))
 (not (clear c))
 (ontable c)
 (= (on c) nob)
 (not (clear e))
 (= (on e) c)
 (not (ontable e))
 (not (clear b))
 (= (on b) f)
 (not (ontable b))
 (clear a)
 (= (on a) d)
 (not (ontable a))
)
(:global-goal (and
 (= (on e) f)
 (= (on f) a)
 (= (on a) b)
 (= (on b) c)
 (= (on c) d)
)))
