(define (problem BLOCKS-8-1)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 f b g c h e a d - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r1 r2 r3)
)
(:init
 (myAgent r0)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (clear f)
 (ontable f)
 (= (on f) nob)
 (not (clear b))
 (= (on b) g)
 (not (ontable b))
 (not (clear g))
 (ontable g)
 (= (on g) nob)
 (not (clear c))
 (ontable c)
 (= (on c) nob)
 (clear h)
 (= (on h) a)
 (not (ontable h))
 (clear e)
 (= (on e) c)
 (not (ontable e))
 (not (clear a))
 (= (on a) b)
 (not (ontable a))
 (clear d)
 (ontable d)
 (= (on d) nob)
)
(:global-goal (and
 (= (on c) d)
 (= (on d) b)
 (= (on b) g)
 (= (on g) f)
 (= (on f) h)
 (= (on h) a)
 (= (on a) e)
)))
