(define (problem BLOCKS-17-0)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 c d e f b i j a n o k m p h g l q - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r0 r2 r3)
)
(:init
 (myAgent r1)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear c))
 (= (on c) o)
 (not (ontable c))
 (not (clear d))
 (= (on d) c)
 (not (ontable d))
 (not (clear e))
 (= (on e) k)
 (not (ontable e))
 (not (clear f))
 (= (on f) e)
 (not (ontable f))
 (not (clear b))
 (= (on b) m)
 (not (ontable b))
 (not (clear i))
 (= (on i) b)
 (not (ontable i))
 (not (clear j))
 (= (on j) i)
 (not (ontable j))
 (not (clear a))
 (= (on a) j)
 (not (ontable a))
 (not (clear n))
 (ontable n)
 (= (on n) nob)
 (not (clear o))
 (ontable o)
 (= (on o) nob)
 (not (clear k))
 (ontable k)
 (= (on k) nob)
 (not (clear m))
 (ontable m)
 (= (on m) nob)
 (clear p)
 (ontable p)
 (= (on p) nob)
 (clear h)
 (= (on h) n)
 (not (ontable h))
 (clear g)
 (= (on g) d)
 (not (ontable g))
 (clear l)
 (= (on l) f)
 (not (ontable l))
 (clear q)
 (= (on q) a)
 (not (ontable q))
)
(:global-goal (and
 (= (on q) n)
 (= (on n) l)
 (= (on l) o)
 (= (on o) j)
 (= (on j) h)
 (= (on h) c)
 (= (on c) e)
 (= (on e) m)
 (= (on m) p)
 (= (on p) a)
 (= (on a) g)
 (= (on g) b)
 (= (on b) i)
 (= (on i) k)
 (= (on k) f)
 (= (on f) d)
)))
