(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
 satellite0 satellite1 satellite2 satellite3 satellite4 - satellite
 instrument0 instrument1 instrument2 instrument3 instrument4 instrument5 instrument6 instrument7 instrument8 instrument9 instrument10 instrument11 instrument12 instrument13 instrument14 instrument15 instrument16 instrument17 instrument18 instrument19 instrument20 instrument21 instrument22 instrument23 instrument24 - instrument
 image4 spectrograph6 infrared2 image5 thermograph1 infrared7 spectrograph0 infrared3 - mode
 star1 groundstation4 star2 star3 groundstation0 phenomenon5 star6 phenomenon7 phenomenon8 planet9 star10 phenomenon11 star12 phenomenon13 star14 planet15 star16 planet17 star18 star19 phenomenon20 planet21 planet22 star23 phenomenon24 - direction
)
(:shared-data
  ((pointing ?s - satellite) - direction)
  (have_image ?d - direction ?m - mode) - (either satellite0 satellite2 satellite3 satellite4)
)
(:init (mySatellite satellite1)
 (power_avail satellite1)
 (not (power_on instrument0))
 (not (calibrated instrument0))
 (= (calibration_target instrument0) groundstation0)
 (not (power_on instrument1))
 (not (calibrated instrument1))
 (= (calibration_target instrument1) star3)
 (not (power_on instrument2))
 (not (calibrated instrument2))
 (= (calibration_target instrument2) star1)
 (not (power_on instrument3))
 (not (calibrated instrument3))
 (= (calibration_target instrument3) star1)
 (not (power_on instrument4))
 (not (calibrated instrument4))
 (= (calibration_target instrument4) star3)
 (not (power_on instrument5))
 (not (calibrated instrument5))
 (= (calibration_target instrument5) groundstation4)
 (not (power_on instrument6))
 (not (calibrated instrument6))
 (= (calibration_target instrument6) star3)
 (not (power_on instrument7))
 (not (calibrated instrument7))
 (= (calibration_target instrument7) star2)
 (not (power_on instrument8))
 (not (calibrated instrument8))
 (= (calibration_target instrument8) star1)
 (not (power_on instrument9))
 (not (calibrated instrument9))
 (= (calibration_target instrument9) star3)
 (not (power_on instrument10))
 (not (calibrated instrument10))
 (= (calibration_target instrument10) groundstation4)
 (not (power_on instrument11))
 (not (calibrated instrument11))
 (= (calibration_target instrument11) star2)
 (not (power_on instrument12))
 (not (calibrated instrument12))
 (= (calibration_target instrument12) star3)
 (not (power_on instrument13))
 (not (calibrated instrument13))
 (= (calibration_target instrument13) star2)
 (not (power_on instrument14))
 (not (calibrated instrument14))
 (= (calibration_target instrument14) groundstation4)
 (not (power_on instrument15))
 (not (calibrated instrument15))
 (= (calibration_target instrument15) star1)
 (not (power_on instrument16))
 (not (calibrated instrument16))
 (= (calibration_target instrument16) star2)
 (not (power_on instrument17))
 (not (calibrated instrument17))
 (= (calibration_target instrument17) groundstation0)
 (not (power_on instrument18))
 (not (calibrated instrument18))
 (= (calibration_target instrument18) star2)
 (not (power_on instrument19))
 (not (calibrated instrument19))
 (= (calibration_target instrument19) star3)
 (not (power_on instrument20))
 (not (calibrated instrument20))
 (= (calibration_target instrument20) star2)
 (not (power_on instrument21))
 (not (calibrated instrument21))
 (= (calibration_target instrument21) groundstation4)
 (not (power_on instrument22))
 (not (calibrated instrument22))
 (= (calibration_target instrument22) star2)
 (not (power_on instrument23))
 (not (calibrated instrument23))
 (= (calibration_target instrument23) star3)
 (not (power_on instrument24))
 (not (calibrated instrument24))
 (= (calibration_target instrument24) groundstation0)
 (not (have_image phenomenon5 infrared7))
 (not (have_image phenomenon5 image4))
 (not (have_image phenomenon7 thermograph1))
 (not (have_image planet9 spectrograph0))
 (not (have_image planet9 spectrograph6))
 (not (have_image star10 infrared3))
 (not (have_image star10 spectrograph6))
 (not (have_image phenomenon11 infrared2))
 (not (have_image star12 spectrograph6))
 (not (have_image star12 thermograph1))
 (not (have_image phenomenon13 infrared7))
 (not (have_image phenomenon13 infrared2))
 (not (have_image star14 infrared2))
 (not (have_image planet15 infrared2))
 (not (have_image star16 image4))
 (not (have_image planet17 image5))
 (not (have_image planet17 image4))
 (not (have_image star18 infrared2))
 (not (have_image star19 infrared3))
 (not (have_image star19 thermograph1))
 (not (have_image phenomenon20 spectrograph0))
 (not (have_image planet21 infrared3))
 (not (have_image planet21 image5))
 (not (have_image planet22 infrared2))
 (not (have_image star23 infrared2))
 (not (have_image phenomenon24 spectrograph6))
 (not (have_image phenomenon24 image5))
 (= (pointing satellite1) planet21)
 (= (on_board satellite1) {instrument3 instrument4 instrument5 instrument6 instrument7})
 (not (= (on_board satellite1) {instrument0 instrument1 instrument2 instrument8 instrument9 instrument10 instrument11 instrument12 instrument13 instrument14 instrument15 instrument16 instrument17 instrument18 instrument19 instrument20 instrument21 instrument22 instrument23 instrument24}))
 (= (supports instrument0) {image4 infrared2})
 (not (= (supports instrument0) {spectrograph6 image5 thermograph1 infrared7 spectrograph0 infrared3}))
 (= (supports instrument1) {spectrograph0})
 (not (= (supports instrument1) {image4 spectrograph6 infrared2 image5 thermograph1 infrared7 infrared3}))
 (= (supports instrument2) {thermograph1 spectrograph0 infrared3})
 (not (= (supports instrument2) {image4 spectrograph6 infrared2 image5 infrared7}))
 (= (supports instrument3) {image5 thermograph1})
 (not (= (supports instrument3) {image4 spectrograph6 infrared2 infrared7 spectrograph0 infrared3}))
 (= (supports instrument4) {spectrograph0})
 (not (= (supports instrument4) {image4 spectrograph6 infrared2 image5 thermograph1 infrared7 infrared3}))
 (= (supports instrument5) {spectrograph6 thermograph1 spectrograph0})
 (not (= (supports instrument5) {image4 infrared2 image5 infrared7 infrared3}))
 (= (supports instrument6) {image5 infrared7})
 (not (= (supports instrument6) {image4 spectrograph6 infrared2 thermograph1 spectrograph0 infrared3}))
 (= (supports instrument7) {spectrograph6 thermograph1 spectrograph0})
 (not (= (supports instrument7) {image4 infrared2 image5 infrared7 infrared3}))
 (= (supports instrument8) {infrared7 infrared3})
 (not (= (supports instrument8) {image4 spectrograph6 infrared2 image5 thermograph1 spectrograph0}))
 (= (supports instrument9) {spectrograph0})
 (not (= (supports instrument9) {image4 spectrograph6 infrared2 image5 thermograph1 infrared7 infrared3}))
 (= (supports instrument10) {image4 image5 infrared7})
 (not (= (supports instrument10) {spectrograph6 infrared2 thermograph1 spectrograph0 infrared3}))
 (= (supports instrument11) {infrared2})
 (not (= (supports instrument11) {image4 spectrograph6 image5 thermograph1 infrared7 spectrograph0 infrared3}))
 (= (supports instrument12) {thermograph1})
 (not (= (supports instrument12) {image4 spectrograph6 infrared2 image5 infrared7 spectrograph0 infrared3}))
 (= (supports instrument13) {infrared3})
 (not (= (supports instrument13) {image4 spectrograph6 infrared2 image5 thermograph1 infrared7 spectrograph0}))
 (= (supports instrument14) {infrared2 thermograph1})
 (not (= (supports instrument14) {image4 spectrograph6 image5 infrared7 spectrograph0 infrared3}))
 (= (supports instrument15) {infrared2})
 (not (= (supports instrument15) {image4 spectrograph6 image5 thermograph1 infrared7 spectrograph0 infrared3}))
 (= (supports instrument16) {image4 spectrograph6})
 (not (= (supports instrument16) {infrared2 image5 thermograph1 infrared7 spectrograph0 infrared3}))
 (= (supports instrument17) {image4 image5 infrared7})
 (not (= (supports instrument17) {spectrograph6 infrared2 thermograph1 spectrograph0 infrared3}))
 (= (supports instrument18) {image4 spectrograph6})
 (not (= (supports instrument18) {infrared2 image5 thermograph1 infrared7 spectrograph0 infrared3}))
 (= (supports instrument19) {spectrograph6 infrared7 infrared3})
 (not (= (supports instrument19) {image4 infrared2 image5 thermograph1 spectrograph0}))
 (= (supports instrument20) {infrared2 infrared3})
 (not (= (supports instrument20) {image4 spectrograph6 image5 thermograph1 infrared7 spectrograph0}))
 (= (supports instrument21) {infrared2 thermograph1})
 (not (= (supports instrument21) {image4 spectrograph6 image5 infrared7 spectrograph0 infrared3}))
 (= (supports instrument22) {image5 thermograph1})
 (not (= (supports instrument22) {image4 spectrograph6 infrared2 infrared7 spectrograph0 infrared3}))
 (= (supports instrument23) {thermograph1 infrared7})
 (not (= (supports instrument23) {image4 spectrograph6 infrared2 image5 spectrograph0 infrared3}))
 (= (supports instrument24) {spectrograph0 infrared3})
 (not (= (supports instrument24) {image4 spectrograph6 infrared2 image5 thermograph1 infrared7}))
)
(:global-goal (and
 (= (pointing satellite0) planet17)
 (have_image phenomenon5 infrared7)
 (have_image phenomenon5 image4)
 (have_image phenomenon7 thermograph1)
 (have_image planet9 spectrograph0)
 (have_image planet9 spectrograph6)
 (have_image star10 infrared3)
 (have_image star10 spectrograph6)
 (have_image phenomenon11 infrared2)
 (have_image star12 spectrograph6)
 (have_image star12 thermograph1)
 (have_image phenomenon13 infrared7)
 (have_image phenomenon13 infrared2)
 (have_image star14 infrared2)
 (have_image planet15 infrared2)
 (have_image star16 image4)
 (have_image planet17 image5)
 (have_image planet17 image4)
 (have_image star18 infrared2)
 (have_image star19 infrared3)
 (have_image star19 thermograph1)
 (have_image phenomenon20 spectrograph0)
 (have_image planet21 infrared3)
 (have_image planet21 image5)
 (have_image planet22 infrared2)
 (have_image star23 infrared2)
 (have_image phenomenon24 spectrograph6)
 (have_image phenomenon24 image5)
))
)
