(define (problem BLOCKS-11-1)
(:domain ma-blocksworld)
(:objects
 r0 r1 r2 r3 - robot
 e j d c f k h g a i b - block
)
(:shared-data
  ((on ?b - block) - block)
  (ontable ?b - block)
  (clear ?b - block)
  ((holding ?r - robot) - block) - 
(either r0 r1 r2)
)
(:init
 (myAgent r3)
 (= (holding r0) nob)
 (= (holding r1) nob)
 (= (holding r2) nob)
 (= (holding r3) nob)
 (not (clear e))
 (= (on e) k)
 (not (ontable e))
 (clear j)
 (= (on j) i)
 (not (ontable j))
 (clear d)
 (= (on d) c)
 (not (ontable d))
 (not (clear c))
 (= (on c) h)
 (not (ontable c))
 (clear f)
 (= (on f) e)
 (not (ontable f))
 (not (clear k))
 (ontable k)
 (= (on k) nob)
 (not (clear h))
 (ontable h)
 (= (on h) nob)
 (clear g)
 (= (on g) b)
 (not (ontable g))
 (not (clear a))
 (ontable a)
 (= (on a) nob)
 (not (clear i))
 (ontable i)
 (= (on i) nob)
 (not (clear b))
 (= (on b) a)
 (not (ontable b))
)
(:global-goal (and
 (= (on b) d)
 (= (on d) j)
 (= (on j) k)
 (= (on k) h)
 (= (on h) a)
 (= (on a) c)
 (= (on c) f)
 (= (on f) g)
 (= (on g) i)
 (= (on i) e)
)))
